<script src="/js/jquery-ui-1.10.3.custom.min.js"></script>
<?require_once(APPLICATION_PATH . '/views/scripts/partial/subnav_admin.phtml'); ?>
<div class="row">
    <div class="panel seven columns centered">
        <p>Create categories (format: first level category > second level category > third level category ...)</p>
        <div class="alert-box error" style="display: none;">Operation Failed!</div>
        <table style="width:500px;">
            <thead>
                <th>Category</th>
                <th></th>
                <th></th>
                <th></th>
            </thead>
            <tbody class="category-item">
                <? foreach ($this->categories as $i => $category) { ?>
                    <tr>
                        <td colspan="3" class="category_string" data-id="<?= $category['id'] ?>"><?= $category['path'] ?></td>
                        <td><a class="small secondary button delete_category radius">Delete</a></td>
                    </tr>
                <? } ?>
            </tbody>
        </table>      
    </div>
</div>
<div class="row" style="margin-top:10px;">
     <div class="two columns"></div>
     <div class="six columns" style="padding-left:40px;">
         <input id="category_value" type="text" placeholder="Enter a new category" size="1024"></td>
     </div>
     <div class="four columns" style="padding-top: 3px;">
         <a id="add_category" class="medium alert button radius small">Add</a>
     </div>
</div>