<script type="text/javascript" src="../js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">

 tinyMCE.init({
   mode : "textareas",
   visual : false,
   theme : "advanced",
   plugins : "preview",
   height : "400",
   theme_advanced_path : false,
   theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,fontselect,fontsizeselect, |search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
   protect: [/{{[#/^].+?}}/g],
   forced_root_block: false
 });

</script>

<?require_once(APPLICATION_PATH . '/views/scripts/partial/subnav_admin.phtml'); ?>

<div class="small-9 medium-9 large-10 columns" style="margin-top: 100px;">
    <div class="row">
        <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
        <div class="small-8 medium-8 large-8 columns alert-field"></div>
    </div>
    <form action="" data-abide="ajax" id="edit-form" class="columns dashboard-form" method="post">
        <input type="hidden" id="tpl_id" name="id" value="<?=default2String($this->tpl['id'])?>">
        <div class="row field data-abide-input-container">
            <div class="small-4 medium-4 large-4 columns">
                <label for="type" class="required">Type</label>
            </div>
            <div class="small-8 medium-8 large-8 columns">
                <input type="text" id="type" name="type" value="<?=default2String($this->tpl['type'])?>" required>
                <small class="error">Type is required.</small>
            </div>
        </div>
        <div class="row field data-abide-input-container">
            <div class="small-4 medium-4 large-4 columns">
                <label for="status" class="required">Status</label>
            </div>
            <div class="small-8 medium-8 large-8 columns">
                <select type="text" id="status" name="status" required>
                    <option value="2" <?if(default2String($this->tpl['status']) == 1){ echo 'selected';}?>>ACTIVATED</option>
                    <option value="1" <?if(default2String($this->tpl['status']) == 1){ echo 'selected';}?>>PENDING</option>
                    <option value="127" <?if(default2String($this->tpl['status']) == 127){ echo 'selected';}?>>DELETED</option>
                </select>
                <small class="error">Status is requried</small>
            </div>
        </div>
        <div class="row field data-abide-input-container">
            <div class="small-4 medium-4 large-4 columns">
                <label for="template_engine" class="required">Template Engine</label>
            </div>
            <div class="small-8 medium-8 large-8 columns">
                <select type="text" id="template_engine" name="template_engine" required>
                    <option value="mustache">Mustache</option>
                    <option value="php" <? if(default2String($this->tpl['template_engine']) == 'php'){ echo 'selected';}?>>PHP</option>
                </select>
                <small class="error">Template Engine is required.</small>
            </div>
        </div>        
        <div class="row field data-abide-input-container">
            <div class="small-4 medium-4 large-4 columns">
                <label for="subject" class="required">Subject</label>
            </div>
            <div class="small-8 medium-8 large-8 columns">
                <input name="subject" type="text" id="subject" value="<?=default2String($this->tpl['subject'])?>" required>
                <small class="error">Subject is required.</small>
            </div>
        </div>
        <div class="row field data-abide-input-container">
            <div class="small-4 medium-4 large-4 columns">
                <label for="header">Header</label>
            </div>
            <div class="small-8 medium-8 large-8 columns">
                <select type="text" id="header" name="header">
                    <option value=""> ---- </option>
                    <?foreach($this->email_tpls as $tpl) {?>
                    <option value="<?=$tpl['type']?>" <?if($tpl['type']==$this->tpl['header']){echo 'selected';}?>><?=$tpl['type']?></option>
                    <? } ?>
                </select>
            </div>
        </div>
        <div class="row field data-abide-input-container">
            <div class="small-4 medium-4 large-4 columns">
                <label for="content" class="required">Content</label>
            </div>
            <div class="small-8 medium-8 large-8 columns">
                <textarea id="content" name="content" style="min-height:250px;"><?=default2String($this->tpl['content'])?></textarea>
            </div>
        </div>
        <br>
        <div class="row field data-abide-input-container">
            <div class="small-4 medium-4 large-4 columns">
                <label for="footer">Footer</label>
            </div>
            <div class="small-8 medium-8 large-8 columns">
                <select type="text" id="footer" name="footer">
                    <option value=""> ---- </option>
                    <?foreach($this->email_tpls as $tpl) {?>
                    <option value="<?=$tpl['type']?>" <?if($tpl['type']==$this->tpl['footer']){echo 'selected';}?>><?=$tpl['type']?></option>
                    <? } ?>
                </select>
            </div>
        </div>
        <div class="row field submit-field">
            <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
            <div class="small-8 medium-8 large-8 columns">
                <input type="submit" id="submit-button" class="submit-button" value="SAVE">
            </div>
        </div>

        <div class="row field submit-field">
            <h2>Available Variables</h2>
            <ul>
                <li>site_url</li>
                <li>site_logo</li>
                <li>user_email</li>
                <li>user_password(dummy)</li>
                <li>user_first_name</li>
                <li>user_last_name</li>
                <li>user_verification_link</li>
                <li>store_url</li>
                <li>store_logo</li>
                <li>store_name</li>
                <li>store_description</li>
            </ul>
        </div>

    </form>
</div>
