<?require_once(APPLICATION_PATH . '/views/scripts/partial/subnav_admin.phtml'); ?>
<div class="row">
    <div class="twleve colums submit_button">
        <a class="button success small creatmasspay">Create a Mass Pay CSV</a>
    </div>
</div>
<div class="row submit_button">
    <p>Status: 0 -- CREATED 4 -- PROCESSING 5 -- PROCESSED</p>
</div>
<div class="main row">
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Status</th>
                <th>PaymentId</th>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Currency</th>   
                <th>Amt</th>
                <th>Contract</th>
                <th>StoreId</th>
                <th>OrderId</th>
                <th>SaleId</th>
                <th>Created</th>
                <th>Updated</th>                
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->payments as $payment){?>
            <tr>
                <td><?=$payment['id'];?></td>
                <td><input type="text" class="edit_status" value="<?=$payment['status'];?>"></input></td>
                <td><?=$payment['payment_id'];?></td>
                <td><?=$payment['sender'];?></td>
                <td class="receiver"><?=$payment['receiver'];?></td>
                <td><?=$payment['currency_code']?></td>
                <td><?=$payment['amt'];?></td>
                <td><?=$payment['contract'];?></td>
                <td><?=$payment['store_id'];?></td>
                <td><?=$payment['order_id'];?></td>
                <td><?=$payment['sale_id'];?></td>
                <td><?=$payment['created'];?></td>                
                <td><?=$payment['updated'];?></td>                
            </tr>
            <?php }?>
        </tbody>
    </table>
    <?php echo $this->pagination($this->total_rows, $this->rows_per_page, $this->page_num); ?>    
</div>
