<link rel="stylesheet" href="/v2/css/pages/pricingpage.css">
<div id="pricingpage" class="row page-layout">

    <section class="small-12 medium-12 large-9 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">Buyer Protection Program</h1>
        </header>
        <div class="main">
            <p>
                Our Shopintoit Buyer Protection program allows for a 30-day post order period where if there is any unresolved issue with your order, you can request a full refund. Please report any issues to <a href="mailto:">support@shopintoit.com</a> with the order number.
            </p>
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>