<link rel="stylesheet" href="/v2/css/pages/pricingpage.css">
<div id="pricingpage" class="row page-layout">

    <section class="small-12 medium-12 large-9 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">Pricing Plan</h1>
        </header>
        <div class="main">
            <div class="clearfix pricing-plans">
                <!--<a class="small-4 medium-4 large-4 columns plan-item" title="Free Plan" href="#">
                    <div class="module-header plan-item-header">
                        <h2 class="title">FREE Plan</h2>
                    </div>

                    <p class="plan-item-pricing"><strong>5%</strong><br><em>per order price</em></p>
                    <p class="plan-item-preferenrial"><strong>Regular</strong><br><em>Paypal fees</em></p>
                    <p class="divider"></p>
                    <p class="plan-item-max"><strong>200</strong> max listed items</p>
                    <p class="text-center plan-item-button"><span>Register</span></p>
                </a>

                <a class="small-4 medium-4 large-4 columns plan-item unavailable" title="Kiosk Plan" href="#">
                    <div class="module-header plan-item-header">
                        <h2 class="title">KIOSK Plan</h2>
                    </div>

                    <p class="plan-item-pricing"><strong>$0.1</strong><br><em>each listed item per month <sup>*1</sup></em></p>
                    <p class="plan-item-preferenrial"><strong>Regular</strong><br><em>Paypal fees</em></p>
                    <p class="divider"></p>
                    <p class="plan-item-max"><strong>500</strong> max listed items</p>
                    <p class="text-center plan-item-button"><span>Ugrade</span></p>
                    <p class="plan-item-extra"><em>30 days free!</em></p>
                </a>
                -->
                <div class="small-2 medium-3 large-3 columns">&nbsp;</div>
                <a class="small-8 medium-6 large-6 columns plan-item" title="Store Plan" href="#">
                    <div class="module-header plan-item-header">
                        <h2 class="title">Store Plan</h2>
                    </div>

                    <p><strong>5% payment transaction fee</strong></p>
                    <p><strong>5% commission rate</strong><br></p>
                    <p class="divider"></p>
                    <p><strong>Customer Support: </strong>Email and Phone</p>
                    <p>Multi Social Platform Image Support</p>
                    <p>CartChart Analytics Supported</p>
                    <p>Social Affiliate Rewards</p>
                    <p>Multi Currency Support</p>
                    <p><strong>Unlimited</strong> Sales per Month</p>
                    <p>Unlimited listed items</p>
                    <p class="text-center plan-item-button"><span>Signup</span></p>
                </a>
                <div class="small-2 medium-3 large-3 columns">&nbsp;</div>
                <!-- <div class="unavailable-mark">Available<br>in future</div> -->
            </div>
            <!--
            <ul class="large-12 columns no-bullet sups">
                <li><sup>*</sup> <strong>$1</strong> minimumn charge apply</li>
            </ul>
            -->
        </div>
    </section>
    <!-- pricing plan end -->

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
