<div class="main row">
<div class="twelve columns">
<div id="page"class="attached">
				
        <div id="hero" class="attached row">

                <h1>Page <span class="gentium">not</span> Found</h1>

                    <div class="panel eight columns centered">
                              <div class="row">
                                <div class="twelve columns">
                                    Sorry but the page you are looking for does not exist.
                              </div>  
                    </div>
                </div>
        </div><!-- end hero -->
</div><!-- end page -->
</div>
</div>