<script type="text/javascript" src="/js/fileuploader.js"></script>
<link rel="stylesheet" href="/css/fileuploader.css"/>

<div id="container" class="row">
<div class="twelve columns">
<? require_once(APPLICATION_PATH.'/views/scripts/partial/subnav.phtml');?>
            <h1>Edit <span class="gentium">your</span> Profile</h1>

            <div class="row">
                <div id="profile" class="panel twelve columns centered">
                     <?foreach($this->errnos as $key=>$value) {?>
                    <div class="alert-box <?echo error_type($key);?> row">
                            <?=$this->errors[$key]['msg']?>
                            <a href="" class="close">&times;</a>
                        </div>
                    <?}?>
                    <form method="post">
                        <div class="row">
                            <div class="five columns">
                                <div class="row">
                                    <div class="twelve columns">
                                    	<label>
                                        	Username <a class="tooltips" href="#">?<span class="tip">At this time you can not edit your username.</span></a>
                                        	<input name="username" type="text" placeholder="Email" value="<?php echo $this->profile->username; ?>" disabled/>
                                        </label>
                                    </div>
                                </div>
                                <div class="row collapse">
                                	<label>Your Pinterest URL</label>
                                    <div class="five columns">
                                        <span class="prefix">http://pinterest.com/</span>
                                    </div>
                                    <div class="seven columns">
                                        <input name ="pinterest_username" type="text" placeholder="Username" value="<?php echo $this->profile->pinterest_username; ?>">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="twelve columns">
                                    	<br><br><a class="button secondary medium" id="changepswrd">Edit Your Password</a>
                                    </div>
                                </div>

                            </div>
                            <div class="five columns push-one">
                                <div class="row">
                                    <div class="twelve columns">
                                    	<label>Address 1 <a class="tooltips" href="#">Why do we need this?<span class="tip">For added security of our marketplace, we require your address as a seller. Your address will not be shared with anyone.</span></a>
                                    	<input name="addr1" type="text" placeholder="Address 1" value="<?php echo $this->profile->addr1; ?>"/></label>
                                        <label>Address 2<input name="addr2" type="text" placeholder="Address 2" value="<?php echo $this->profile->addr2; ?>"/></label>

                                        <div class="row">
                                        <div class="five columns">
                                        	<label>City<input name="city" type="text" placeholder="City" value="<?php echo $this->profile->city; ?>"/></label>
                                        </div>
                                        <div class="four columns">
	                                        <label>State<input name="state" type="text" placeholder="State" value="<?php echo $this->profile->state; ?>"/></label>
                                        </div>
                                        <div class="three columns">
    	                                    <label>Zip<input name="zip" type="text" placeholder="Zip Code" value="<?php echo $this->profile->zip; ?>"/></label>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                                <br>
                            </div>
                        </div>

                        <div class="row">
                            <button id="getstartedbutton" name="submit" type="submit" value="submit" class="button radius alert large" >Save Profile</button>
                        </div>
                    </form>
                </div><!-- end profile -->
            </div>
	</div><!-- end content -->
</div>
</div><!-- end container -->




<div id="myModal" class="reveal-modal">
  <h3>Change Password</h3>
  <div id="save_password_error_box" class="alert-box alert" style="display: none;">Errors on changing your password!</div>
  <label>Current Password<input id="current_password" name="current_password" type="password" placeholder="Current Password" value=""/></label>
  <hr>
  <label>New Password<input id="new_password" name="new_password" type="password" placeholder="New Password" value=""/></label>
  <label>Confirm New Password<input id="confirm_password" name="confirm_password" type="password" placeholder="Confirm New Password" value=""/></label><br>
  <button id="save_password" name="submit" type="submit" value="submit" class="button radius alert large" >Save</button>
  <a class="close-reveal-modal button radius secondary large">Cancel</a>
  <a class="close-reveal-modal">&#215;</a>
</div>
