<link rel="stylesheet" href="/v2/css/pages/dashboard.css">
<div id="dashboard" class="row page-layout dashboard">

    <section class="small-12 medium-12 large-9 columns">
        <div class="row">
            <div class="small-3 medium-3 large-2 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/left_sidebar.phtml');?>
            </div>
            <!-- side nav end -->

            <div id="solidus-publish" class="small-9 medium-9 large-10 columns">
                <div class="solidus-header">
                    <div class="small-7 medium-8 large-8 columns">
                        <h3 class="title">Current Exchange Rate<br><strong>0.621</strong></h3>
                    </div>
                     <div class="small-5 medium-4 large-4 columns">
                        <h3 class="title">My Solidus<br><strong>56.21</strong></h3>
                     </div>
                </div>

                <ul class="dashboard-subnav">
                    <li class="active"><a href="/solidus/publish">Publish</a></li>
                    <li><a href="/solidus/exchange">Exchange</a></li>
                </ul>
                <!-- dashboard sub nav end -->

                <div class="module-tools">
                    <div class="small-7 medium-7 large-7 columns">
                        <div class="module-tools-item">
                            <a class="addnew add-new-products"><i class="icon fi-plus"></i><span>Add Products</span></a>
                        </div>
                    </div>
                    <div class="small-5 medium-5 large-5 columns">
                        <form action="" class="module-search glass-right" data-search>
                            <input type="text" class="search-input hidden">
                            <a href="javascript:;" class="search-submit"><i class="icon fi-magnifying-glass"></i></a>
                        </form>
                    </div>
                </div>

                <div class="dashboard-table">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="checkbox"><input type="checkbox"></th>
                                <th class="action">Action</th>
                                <th class="name">Name</th>
                                <th class="number">Product Number</th>
                                <th class="shared">Shared</th>
                                <th class="bought">Bought</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="checkbox"><input type="checkbox"></td>
                                <td class="action">Cancel</td>
                                <td class="name">This is a Product Name</td>
                                <td class="number">900-108076</td>
                                <td class="shared">2</td>
                                <td class="bought">2</td>
                            </tr>
                            <tr>
                                <td class="checkbox"><input type="checkbox"></td>
                                <td class="action">Cancel</td>
                                <td class="name">This is a Product Name</td>
                                <td class="number">900-108076</td>
                                <td class="shared">2</td>
                                <td class="bought">2</td>
                            </tr>
                            <tr>
                                <td class="checkbox"><input type="checkbox"></td>
                                <td class="action">Cancel</td>
                                <td class="name">This is a Product Name</td>
                                <td class="number">900-108076</td>
                                <td class="shared">2</td>
                                <td class="bought">2</td>
                            </tr>
                        </tbody>
                    </table>

                    <ul class="pagination">
                        <li class="arrow unavailable"><a href="">Prev</a></li>
                        <li class="current"><a href="">1</a></li>
                        <li><a href="">2</a></li>
                        <li><a href="">3</a></li>
                        <li><a href="">4</a></li>
                        <li class="unavailable"><a href="">&hellip;</a></li>
                        <li><a href="">12</a></li>
                        <li><a href="">13</a></li>
                        <li class="arrow"><a href="">Next</a></li>
                    </ul>
                </div>
                <!-- table end -->

            </div>
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>