<div id="about-page" class="row page-layout about-page">

    <section class="small-12 medium-12 large-9 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">Our Team</h1>
        </header>
        <div class="main">
            <div class="large-12 columns">
                <div class="member">
                    <img src="/v2/img/team-FG.jpg" alt="Francisco Guerrero" class="member-avatar">
                    <div class="content">
                        <h4 class="title">Francisco Guerrero</h4>
                        <p>Francisco is a serial entrepreneur, bringing over 10 years of marketing and business development experience to Shopintoit. As VP Marketing, he helped launch MotherKnows.com at TechCrunch Disrupt, and has managed marketing and ecommerce at Gap, HP, McAfee and YouSendIt among others. Francisco has an MBA from Christian Brothers University and a Digital Marketing 2 year Certificate from SJSU and the DMA.</p>
                    </div>
                </div>
                <div class="member">
                    <img src="/v2/img/team-LH.jpg" alt="Liang Huang" class="member-avatar">
                    <div class="content">
                        <h4 class="title">Liang Huang</h4>
                        <p>Liang is a rockstar engineer, bringing over 5 years of software development experience to Shopintoit. Prior to Shopintoit, he was Software Engineer at Yahoo!, Federated Media, and KickApps, etc., where his contributions spanned from creating ad serving platform to designing/developing data intensive social features. Liang holds a MS in Computer Science from University of Mississippi.</p>
                    </div>
                </div>
                <div class="member">
                    <img src="/v2/img/team-TH.jpg" alt="Tommy Hodgins" class="member-avatar">
                    <div class="content">
                        <h4 class="title">Tommy Hodgins</h4>
                        <p>Tommy is a creative designer, bringing over 8 years of UI/UX design experience to Shopintoit. Prior to Shopintoit, he managed Engine Communications where he was responsible for branding, graphic & web design. He was acclaimed as “one of the most innovative, refreshing and dedicated visual designers” by his clients.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- pricing plan end -->

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
