<!DOCTYPE html>
<html>
    <head>
        <title>My Page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="//code.jquery.com/mobile/1.3.0-rc.1/jquery.mobile-1.3.0-rc.1.min.css" />
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>
        <script src="//code.jquery.com/mobile/1.3.0-rc.1/jquery.mobile-1.3.0-rc.1.min.js"></script>
    </head>
    <body>

        <div data-role="page">

            <div data-role="header">
                <h1>UI Elements</h1>
            </div><!-- /header -->

            <div data-role="content">
                <p>Hello world</p>
                <!-- listviews -->
                <ul data-role="listview" data-inset="true" data-filter="true">
                    <li><a href="#">Acura</a></li>
                    <li><a href="#">Audi</a></li>
                    <li><a href="#">BMW</a></li>
                    <li><a href="#">Cadillac</a></li>
                    <li><a href="#">Ferrari</a></li>
                </ul>
                <!-- Slider -->
                <form>
                    <label for="slider-0">Input slider:</label>
                    <input type="range" name="slider" id="slider-0" value="25" min="0" max="100"  />
                </form>
                <!-- Button -->
                <a href="#" data-role="button" data-icon="star">Star button</a>
            </div><!-- /content -->

        </div><!-- /page -->

    </body>
</html>
