<div id="contact-page" class="row page-layout contact-page">

    <section class="small-12 medium-12 large-9 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">Contact Us</h1>
        </header>
        <div class="main">
            <div class="large-12 columns">
                <div class="contact-item">
                    <h3 class="title">Support</h3>
                    <p class="content"><a href="">xxx@shopintoit.com</a></p>
                </div>
                <div class="contact-item">
                    <h3 class="title">Mail</h3>
                    <p class="content">Shopintoit<br>
                    1000 Villa avenue Suite #88<br>
                    San Jose, CA 95126</p>
                </div>
                <div class="contact-item">
                    <h3 class="title">Twitter</h3>
                    <p class="content"><a href="https://twitter.com/shopintoit" target="_blank">@shopintoit</a></p>
                </div>
                <div class="contact-item">
                    <h3 class="title">Facebook</h3>
                    <p class="content"><a href="https://www.facebook.com/shopintoit" target="_blank">https://www.facebook.com/shpintoit</a></p>
                </div>
                <div class="contact-item">
                    <h3 class="title">Press</h3>
                    <p class="content">Contact <a href="mailto:">xxx@shopintoit.com</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- pricing plan end -->

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>