<div id="terms-page" class="row page-layout terms-page">

    <section class="small-12 medium-12 large-9 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">Terms of Service</h1>
        </header>
        <div class="main">
            <div class="large-12 columns">
                <div class="term-item">
                    <h4 class="title">Account Terms</h4>
                    <ol class="list">
                        <li>You must be 18 years or older to use this Service.</li>
                        <li>Sellers: You must provide your full legal name, address for sellers, a valid email address, and any other information needed in order to complete the signup process. You agree that you are the legal owner of the products you sell and all copyright issues have been settled before selling.</li>
                        <li>Buyers: Please provide your email and password or use facebook login to create a buyer account . In order to leave feedback and collect your purchase history we require your name, email address, password for service and zipcode.</li>
                        <li>Resellers and Sharers: You must provide your full legal name, current address for sellers, a valid email address, and any other information needed in order to complete the signup process.</li>
                        <li>You are responsible for keeping your password secure. Shopintoit cannot and will not be liable for any loss or damage from your failure to maintain the security of your account and password.</li>
                        <li>You may not use the Shopintoit service for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws) as well as the laws of California and of your own country, state, city laws.</li>
                        <li>You are responsible for all activity and content (data, graphics, photos, links) that is uploaded under your Shopintoit account.</li>
                        <li>The following items are not allowed to be sold via a Shopintoit online store: Firearms, adult-only materials, any type of medication requiring a prescription in any country, pirated materials, illegal drugs, unauthorized replicas of branded items, organic materials, live plants and animals, clothing listed as previously used.</li>
                        <li>International Sellers : You must abide by the local rules of your own country in addition to the country (countries) where you plan to sell or ship items.</li>
                        <li>International sellers must represent themselves as such, indicate their refund and shipping timelines clearly in their store description.</li>
                        <li>Your associated accounts (Pinterest, Facebook, Twitter,Site) should also not be selling or promoting Firearms, adult-only content, materials and/or gifts, any type of medication requiring a prescription, pirated materials, illegal drugs, unauthorized replicas of branded items, organic materials, live plants, clothing listed as previously used, live animals, banned chemicals.</li>
                        <li>You must not transmit any worms or viruses or any code of a destructive nature.</li>
                        <li>A breach or violation of any of the Account Terms as determined in the sole discretion of Shopintoit will result in an immediate termination of your services.</li>
                    </ol>
                </div>
                <div class="term-item">
                    <h4 class="title">General Conditions</h4>
                    <p class="spec">You must read, agree with and accept all of the terms and conditions contained in this User Agreement and the privacy policy before you may become a member of Shopintoit.</p>
                    <ol class="list">
                        <li>We reserve the right to modify or terminate the Service for any reason, without notice at any time.</li>
                        <li>We reserve the right to refuse service to anyone for any reason at any time.</li>
                        <li>Your use of the Service is at your sole risk. The Service is provided on an ”as is“ and ”as available“ basis without any warranty or condition, express, implied or statutory.</li>
                        <li>Shopintoit does not warrant that the service will be uninterrupted, timely, secure, or error-free.</li>
                        <li>Shopintoit does not warrant that the results that may be obtained from the use of the service will be accurate or reliable.</li>
                        <li>You understand that your Content (not including credit card and other payment forms’ information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit Card information is always encrypted during transfer over networks.</li>
                        <li>We may, but have no obligation to, remove Content and Accounts containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.</li>
                        <li>Sellers: Shopintoit offers  the STORE plan, please consult our page at <a href="/pricing" target="_blank">http://www.shopintoit.com/pricing</a> to see prices and features. All plans have a 30 day trial period. </li>
                        <li>Sellers: Sellers participating in Shopintoit must agree to a mimimum 5% commission to the final seller of the product. This commission can be increased as desired.  Payments are sent every week, on Friday between 2pm-11pm (excluding holidays).</li>
                        <li>Buyers: Shopintoit does not warrant that the quality of any products, services, information, or other material purchased or obtained by you through the Service will meet your expectations, or that any errors in the fulfillment will be corrected by the seller.</li>
                        <li>Re-Sellers and affiliates: Shopintoit will pay a maximum amount of $9,999.99 per month for fees generated via affiliate sales.  Resellers and affiliates pay their own paypal disbursement fee when receiving payments. Affiliate payments are disbursed 30 days after the transaction. Cancelled items are not eligible for commission fees. Resellers must comply with our separate Shopintoit Affiliate program terms of service.</li>
                        <li>Sellers, Buyers and Resellers own responsibility to pay their taxes on their online purchases and sales. We offer you the ability to add taxes to your sale transaction.</li>
                        <li>Sellers: You must respond to our email or phone queries/questions within 7 days in case of research and return issues. Failure to do so may result in refund provided to buyer.</li>
                        <li>Shopintoit users who select Paypal are bound by Paypal’s terms of service (<a href="https://www.paypal.com/cgi-bin/webscr?cmd=p/gen/terms-outside" target="_blank">https://www.paypal.com/cgi-bin/webscr?cmd=p/gen/terms-outside</a>) in addition to Shopintoit terms of service.</li>
                        <li>You expressly understand and agree that Shopintoit shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses resulting from the use of or inability to use the service.</li>
                        <li>In no event shall Shopintoit or our suppliers be liable for lost profits or any special, incidental or consequential damages arising out of or in connection with our site, our services or this agreement (however arising including negligence). You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, Shopintoit partners, officers, directors, agents, and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your breach of this Agreement or the documents it incorporates by reference, or your violation of any law or the rights of a third party.</li>
                        <li>Technical support is available for everyone. Response time may vary per case.</li>
                        <li>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service without the express written permission by Shopintoit.</li>
                        <li>Verbal or written abuse of any kind (including threats of abuse or retribution) of any Shopintoit customer, Shopintoit employee, member, or officer will result in immediate account termination.</li>
                        <li>We do not claim any intellectual property rights over the material you provide to the Shopintoit service. All material you upload remains yours. You can remove your Shopintoit store at any time by deleting your account. This will also remove all content you have stored on the Service.</li>
                        <li>By uploading images and item description content to Shopintoit.com, you agree to allow other internet users to view them and you agree to allow Shopintoit to display and store them and you agree that Shopintoit can, at any time, review all the content submitted by you to its Service.</li>
                        <li>The failure of Shopintoit to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. The Terms of Service constitutes the entire agreement between you and Shopintoit and govern your use of the Service, superseding any prior agreements between you and Shopintoit (including, but not limited to, any prior versions of the Terms of Service).</li>
                        <li>You retain ownership over all content that you submit to a Shopintoit store however, by making your store public, you agree to allow others to view your content.</li>
                        <li>Shopintoit does not pre-screen Content and it is in their sole discretion to refuse or remove any Content that is available via the Service.</li>
                        <li>Shopintoit will provide seller information when requested by law enforcement, whether a warrant is presented or not.</li>
                        <li>Questions about the Terms of Service should be sent to support at Shopintoit dot com.</li>
                    </ol>
                </div>
                <div class="term-item">
                    <h4 class="title">Payment of Fees and Subscriptions for Sellers</h4>
                    <ol class="list">
                        <li>A valid PayPal account is required for payments to be sent and received and to receive any sales revenue or commission revenue paid.</li>
                        <li>
                            The service will be billed with as follows depending on the plan selected. See <a href="/pricing">pricing page</a> for more updates:
                            <h4 class="title">STORE:</h4>
                            <ol class="list">
                                <li>Paypal payment Fees</li>
                                <li>Paypal disbursement fees</li>
                                <li>5% Transaction fee</li>
                                <li>5% Affiliate fee</li>
                            </ol>
                        </li>
                        <li>International sellers pay the above prices in their local currency.</li>
                        <li>In case of a dispute, seller must provide first proof of shipment within 7 days of a request. If not received, the refund will be given to the buyer and a charge back will be placed on your earnings.</li>
                        <li>Per item fees upon a successful sale are not refundable after 30 days.</li>
                    </ol>
                </div>
                <div class="term-item">
                    <h4 class="title">Disbursement of Funds for Sellers</h4>
                    <ol class="list">
                        <li>A valid PayPal account is required for payments to be sent and received and to receive any sales revenue or commission revenue paid.</li>
                        <li>A tracking delivery number is REQUIRED so that the funds from that purchase are available for the seller to be deposited immediately.</li>
                        <li>Sellers registered with a Credit Card on file get their sales deposited on demand when requested.</li>
                        <li>For purchases over $99.99 USD, both tracking number and a credit card on file are required to make the funds available. Otherwise such funds will be available 14 days after purchase.</li>
                    </ol>
                </div>
                <div class="term-item">
                    <h4 class="title">Cancellation and Termination</h4>
                    <ol class="list">
                        <li>You may cancel your account at anytime by emailing xxx@Shopintoit.com.</li>
                        <li>Once your account is cancelled all of your Content will be immediately deleted from the Service.</li>
                        <li>If you cancel the Service in the middle of the month, you will not receive a pro-rated refund on fees. Any cancelation after day 1 of the 30-day subscription term is billed on its entirety.</li>
                        <li>We reserve the right to modify or terminate the Shopintoit service for any reason, without notice at any time.</li>
                        <li>Fraud: Without limiting any other remedies, Shopintoit may suspend or terminate your account if we suspect that you (by conviction, settlement, insurance or escrow investigation, or, internal investigation or otherwise) have engaged in fraudulent activity in connection with the Site.</li>
                    </ol>
                </div>
                <div class="term-item">
                    <h4 class="title">Modifications to the Terms of Services, fees and subscription prices</h4>
                    <ol class="list">
                        <li>Prices for using Shopintoit are subject to change upon 14 days notice from Shopintoit. Such notice may be provided at any time by posting the changes to the Shopintoit Site (Shopintoit.co) or the administration menu of your Shopintoit store via an announcement.</li>
                        <li>Shopintoit reserves the right at any time to time to modify or discontinue, the Service (or any part thereof) with or without notice.</li>
                        <li>Shopintoit shall not be liable to you or to any third party for any modification, price change, suspension or discontinuance of the Service.</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <!-- pricing plan end -->

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
