<div id="container" class="row">
<div class="twelve columns">
	<? require_once(APPLICATION_PATH.'/views/scripts/partial/subnav.phtml');?>
    <h1>Frequently <span class="gentium">Asked</span> Questions</h1>
    <? require_once(APPLICATION_PATH.'/views/scripts/partial/social_channels.phtml');?>
    <div class="row">
        <div class="panel twelve columns centered">
        	<a id="ssn"></a><h2>ShopInterest Sales Network - For ShopInterest Sellers</h2>
        	
        	<p><strong>What is the ShopInterest Sales Network?</strong></p>
        	
        	<p>The ShopInterest Sales Network is the easiest way to make your ShopInterest Store products available for sell via affiliates. Your products can be sold beyond your ShopInterest store and you determine how much of a commission you are willing to pay.
        	</p>
        	<p><strong>How Does the ShopInterest Sales Network work?</strong></p>
        	<p>
        	Once you indicate in your profile that you want to join, you select the products you want to sell via third parties and set the commission. After that, ShopInterest makes those products available with tracking so that any affiliate network, or third party can display your items in their websites, and once a sale happens, we will take care of the payments for everyone.
        	</p>
        	<p><strong>Do I require a deposit to sell via the ShopInterest Sales Network?</strong></p>
        	<p>
        	No deposit is required since we manage the payments ourselves. However, we do request that you MUST have a detailed return policy on your store profile.
        	</p>
        	<p><strong>Do I need to change any of my payments?</strong></p>
        	<p>
        	No, we'll continue using your PayPal account and will deposit to your account the sales you generate and S&amp;H charges minus the affiliate fee and any of our fees.
        	</p>
        	<p><strong>Can I sell my items via the ShopInterest Sales Network?</strong></p>
        	<p>
        	All the products listed at your ShopInterest store are eligible to be sold via the network. We do exclude certain Adult and offensive novelty items, and excluded items as per the current ShopInterest terms of Service
        	</p>
        	<p><strong>Can I sell other's ShopInterest's products on my site/store/blog?</strong></p>
        	<p>
        	Yes! You can register as well as a third-party seller and joined the ShopInterest Sales Network as a reseller. This is a great way to help other sellers and give your store related products and items that might complement a sale. You get paid and the seller gets a sale, so everyone wins.
        	</p>
        	<p><strong>How much is the cost?</strong></p>
        	<p>
        	As a seller, joining the ShopInterest sales network is free of charge, and you determine the commission to be paid per product.
        	</p>
        	<p><strong>What is the commission paid?</strong></p>
        	<p>
        	You determine the percentage that you are willing to pay for a sale, (with a minimum of $1) and different items can have different rates for more flexibility.
        	</p>
        	<p><strong>What products you recommend to sell via the network?</strong></p>
        	<p>
        	We recommend you sell your best products and those who you have a quantity available on hand. This will give your products more exposure
        	</p>
        	<p><strong>Where are my products sold?</strong></p>
        	<p>
        	We will limit our affiliates and third party sellers to the U.S. only.
        	</p>
        	<p><strong>What happens if a product is canceled or returned?</strong></p>
        	<p>
        	If one of your products is cancelled or return with accordance to your own return policy and no later than 30 days after purchase, you get the affiliate fee returned to you (minus any payment fees)
        	</p>
        	
        	<hr>
        	<a id="ssn3"></a><h2>ShopInterest Sales Network - for Third Party Sellers and Affiliate Networks</h2>
        	
        	<p><strong>What is the ShopInterest Sales Network?</strong></p>
        	<p>
        	The ShopInterest Sales Network is the easiest way to make your ShopInterest Store products available for sell via affiliates. You can now add all of the ShopInterest products available. You can now expand the products you offer with unique products and gifts that can't be find anywhere else.
        	</p>
        	<p><strong>How Does the ShopInterest Sales Network work?</strong></p>
        	<p>
        	Our sellers have made products available for affiliate sales. After you register as an affiliate seller, you can select all the products that pay a commission, we will provide you with trackable links so that any of the sales you drive to the site generate a commission.
        	</p>
        	<p><strong>What are the requirements? </strong></p>
        	<p>
        	Your completed profile registration, agree with the terms and conditions and a verified Paypal account that we can use to deposit your earnings.
        	</p>
        	<p><strong>How much is the cost to enroll? </strong></p>
        	<p>
        	There is no cost to join the Sales Network as an affiliate seller. You can select all the items available that you want to sell via your own sites. You can generate sales of up to $9,999 a month every month.
        	</p>
        	<p><strong>How do you track the sales? </strong></p>
        	<p>
        	The main method of tracking is via URL links. All the items you select will have your affiliate ID in the URL. This is how we track the sales generated. Only items available for affiliates with a trackable URL are eligible for payments. We may also use cookies to track visits for 90 days. Items not listed as available for commissions do not generate commissions for you.
        	</p>
        	<p><strong>When is the commission paid? </strong></p>
        	<p>
        	Commissions are paid 30 days after each sale.
        	</p>
        	<p><strong>How do re-sellers collect their commissions?</strong></p> 
        	<p>
        	Commissions will be deposited to your paypal account.
               </p> 
        </div>
    </div>
	</div><!-- end content -->
</div>       
</div><!-- end container -->
