
<div id="container" class="row">
    <div class="twelve columns">
        <? require_once(APPLICATION_PATH . '/views/scripts/partial/subnav.phtml'); ?>
        <h1>My <span class="gentium">Sales</span> Network</h1>
        <h2>Here are the products in your sales network. Click "Get Code" to view all your sharing options for each product.</h2>
        <?php echo $this->render('associate/search_form.phtml');?>        
        <div class="row">
            <div class="panel twelve columns centered">
                <div class="row">
                    <div class="twelve columns"> 

                        <? foreach ($this->sales_products as $product) {?>
                        <div class="section product_item">
                            <div class="row">
                                <div class="prodimg two columns"><a href="<?=$product['product_url'];?>" target="_blank"><img src="<?=$product['board_img'];?>" alt="" /></a></div>
                                <div class="detail five columns">
                                    <input type="hidden" class="product_name" value="<?=$product['product_name'].',$'.$product['product_price'];?>" />                                        
                                    <h5><?=$product['product_name_shorten'];?></h5>
                                    <div class="fee">Commission Fee: <?=$product['product_commission'];?>%</div>
                                </div>
                                <div class="select five columns"><a href="" class="button radius secondary tiny remove" store_id="<?=$product['store_id'];?>" product_id="<?=$product['product_id'];?>">Remove from Network</a> <button class="button radius alert get_code">Get Code</button></div>
                            </div>
                            <div class="row thecode" style="display:none;">
                                <div class="four columns">
                                    <label>Custom URL</label>
                                    <p>Send this link to your friends.</p>
                                    <input type="text" name="custom_url" class="custom_url" value="<?=$product['product_aff_url'];?>" style="width : 75%; display:inline;"/>
                                    <div class="zeroclipboard-button button radius success small" data-clipboard-text="<?=$product['product_aff_url'];?>" trigger-title="Done" title="Copy to clipboard">Copy</div> 
                                    <label>Text Link</label>
                                    <p>Embed this link on your blog or social network.</p>
                                    <div class="sample" style="display: inline;"><a href="">Sample of text link.</a></div>
                                    <input type="text" name="" value="<?=$product['product_aff_name'];?>" style="width : 75%; display:inline;"/>
                                    <div class="zeroclipboard-button button radius success small" data-clipboard-text="<?=$product['product_aff_name'];?>" trigger-title="Done" title="Copy to clipboard">Copy</div> 
                                </div>
                                <div class="four columns">
                                    <label>Widget Code</label>
                                    <p>Embed this link on your blog or social network.</p>
                                    <input type="text" name="" style="height: 6em;text-align: center;" value="Coming Soon..." disabled />							
                                </div>
                                <div class="four columns social">
                                    <label>Share Now</label>
                                    <p>Click select a social network icon to share with your network.</p>
                                    <a class="fb" href=""></a>
                                    <a class="tw" href=""></a>
                                    <a class="pn" href=""></a>
                                </div>
                                <input type="hidden"  name="share_url" class="share_url" value="<?=$product['product_share_url'];?>" />                                
                            </div>
                        </div>
                        <? }?>
                    </div>
                </div>            
            </div>
        </div>
        <?php echo $this->pagination($this->total_rows, $this->rows_per_page, $this->page_num, $this->extra_params); ?>

    </div><!-- end content -->
</div>       
</div><!-- end container -->

<script src="/js/ZeroClipboard.min.js"></script>
<script src="/js/main.js"></script>