<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>
Dear ShopIntoit Sales Network Seller:<br><br>

Please click on the following link to validate your account and get started:<br><br>

<b><a href="<?=$this->link?>"><?=$this->link?></a></b><br><br>

Thank you for joining our network. The ShopIntoit Sales Network is full on new, unique and beautiful items not available anywhere else to sell via affiliates.<br><br>

Here are a few important items:<br><br>

COSTS & FEES: For now, you can re-sell for FREE.<br><br>

PAYMENTS & RETURNS: We are using PayPal to administer and collect payments. Your payments should be available in your PayPal account no later than 30 days after the purchase. No commissions are paid on refunds and returns.<br><br>

MANAGING INVENTORY - Click on 'Search Products' to add more products to your catalog. Remember we have 1000's of new products every day<br><br>

MARKETING - Make sure to use the links provided in the ads and links you have. We will be adding more tools shortly<br><br>

Thank You - You are awesome!<br><br>

The Shopintoit team<br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
