<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>

Dear <?=$this->first_name?>: <br><br>

The auction <a href="<?=$this->auction_url?>" target="_blank"><?=$this->product_name?></a> has completed,  <?=$this->winner_name?> won it with <?=$this->currency_symbol?><?=$this->bid_price?> offered. <br><br>


Thank You - You are awesome! <br><br>

The Shopintoit team<br>


PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
