<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>
Dear Shopintoit Merchant:<br><br>

Your sale order <b><?=$this->order_num?></b> has been canceled by <?=$this->by?>.<br><br> 

<br>If you have any question about your order, please feel free to contact us.<br>

The Shopintoit team<br>
<a href="<?=$this->site_url?>">Create your own online store &#187;</a><br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
