Dear Shopintoit users,<br><br>

Shopintoit be down for maintenance on Tuesday, November 20th, 2012. Downtime will last 
approximately 3 hours between 7pm to 10:00pm Pacific Time.<br><br>

We're sorry for the inconvenience and thanks for your patience!<br><br>

The Shopintoit team<br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
