<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>
Dear Shopintoit buyer:<br><br>

7 days ago, you shopped with us. Do you like the products you purchased? Do you enjoy the shipping/handling services by the sellers? <br>
Do you want to share your experience with us? We would love to hear from you. Please rate below based on your satisfaction. <br><br>

1 - Not recommended to :  5 - It's amazing!<br><br>

<b><a href="<?=$this->feedback_link?>"><?=$this->feedback_link?></a></b><br><br>

Your feedback is very important for us to create a better e-commerce environment for everybody, including you! We appreciate your input.<br><br> 
  
Thanks!<br><br>

The Shopintoit team<br>
<a href="<?=$this->site_url?>">Create your own online store free &raquo;</a><br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
