<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>
Dear Shopintoit Buyer:<br><br>

Your order <b><?=$this->order_num?></b> has been shipped by the seller.<br><br> 

<?if(!empty($this->shipping_service_provider) || !empty($this->tracking_number) || !empty($this->expected_arrival_date)) {?>
Shipping details:<br><br>
<?if(!empty($this->shipping_service_provider)) {?>
Shipping Service Provider: <?=$this->shipping_service_provider?><br>
<?}?>
<?if(!empty($this->tracking_number)) {?>
Tracking Number: <?=$this->tracking_number?><br>
<?}?>
<?if(!empty($this->expected_arrival_date)) {?>
Expected Arrival Date: <?=$this->expected_arrival_date?><br>
<?}?>
<?}?>

<br>If you have any question about your order, please feel free to contact the seller directly by clicking the<br>
button of "Contact the seller" on the store page <a href="<?=$this->store_url?>"><?=$this->store_url?></a>.<br><br>

Thanks for your purchase with Shopintoit.<br><br>

The Shopintoit team<br>
<a href="<?=$this->site_url?>">Create your own online store &#187;</a><br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
