<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>
Dear Shopintoit buyer:<br><br>

Your order number is <b>#<?='0623-'.$this->store_id.'-'.$this->order_id?></b>. Thanks for your purchase with Shopintoit.<br><br>

<b>Order summary:</b><br><br>
Your order placed on <?=$this->datetime?><br><br>
<table border="1">
	<tr>
		<td>Item</td>
		<td>Quantity</td>
		<td>Price</td>
	</tr>
        <?foreach($this->products as $product) {?>
	<tr>
		<td><?=$product['product_name']?></td>
		<td><?=$product['quantity']?></td>
		<td><?=$product['product_price']?></td>
	</tr>
        <?}?>
</table>
<br>
Subtotal: <?=$this->currency_symbol?><?=$this->price?><br>
Tax: <?=$this->currency_symbol?><?=$this->tax?><br>
Shipping & Handling: <?=empty($this->shipping) ? 'Shipping is free' : $this->currency_symbol.$this->shipping?><br>
<b>Total: <?=$this->currency_symbol?><?=$this->total?></b><br><br>

So what&#39;s next?<br><br>
<ol>
	<li>No need to do anything else! Most orders ship within 10-14 days from the purchase date, but may vary by different sellers.</li>
	<li>Enjoy!</li>
</ol>
<br>
Thanks!<br><br>

The Shopintoit team<br>
<a href="<?=$this->site_url?>">Create your own online store &#187;</a><br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
