<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>

Hi <?=$this->first_name?>:<br><br>

There is a new highest bid <?=$this->currency_symbol?><?=$this->new_bid_price?> on this item, but there's still a chance to make it yours. Increase your bid to have a chance at winning.<br><br>

Bid again on <a href="<?=$this->auction_url?>" target="_blank"><?=$this->product_name?></a> ! This auction ends at <?=$this->end_time?>.<br><br>

Good Luck!<br><br>


Thank You - You are awesome! <br><br>

The Shopintoit team<br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
