<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>

Dear Shopintoit Team: <br><br>

We are in our Sprint <?=$this->sprint_no?> now, and we just release a new version -- <?=$this->release_no?>, and below is the content of the release note in markdown format:<br><br>

<pre>
<?=$this->release_note_content?>
</pre>

<br><br><br><br>

you can find a pretty rendered version of the release note here:
<a href="<?=$this->release_note_github_url?>"><?=$this->release_note_github_url?></a> <br>

Thank You! <br><br>

The Shopintoit Dev Team<br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
