<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>
Dear Shopintoit user:<br><br>

Hey, don't feel bad, we all forget things. :) You have requested to reset your password.<br><br>

Here is your new password:<br><br>

<b><?=$this->password?></b><br><br>

<a href="<?=$this->site_url?>/login">Login here &raquo;</a><br><br>

If you did not request this change, please contact us at <a href="mailto:<?=$this->support_email?>"><?=$this->support_email?></a><br><br>

Thanks!<br><br>

The Shopintoit team<br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
