<a href="<?=$this->site_url?>"><img src="<?= getSiteMerchantUrl(SHOPINTEREST_LOGO);?>"></a><br>
Dear Shopintoit user:<br><br>

Thank you for joining Shopintoit! The best way to connect your merchandise to social media and reward your best followers!<br>

Please click on the following link to validate your account and get started:<br><br>

<b><a href="<?=$this->link?>"><?=$this->link?></a></b><br><br>

Need Launch Help? Check our <a href="<?= getSiteMerchantUrl('/how');?>">How-to Videos</a> and launch in a few minutes !<br><br>

Thank you for your support and congratulations on connecting your store with our platform. We hope your store is hugely successful. <br><br>

Here are a few important points:<br><br><br><br>

- PAYMENTS & RETURNS: We are using PayPal to administer and collect payments, so your payments should be available in your PayPal account no later than 7 days after the purchase. Your store should also clearly display your return policy.<br><br>

- SHIPPING CHARGES - On your profile, we ask you to enter the shipping price that applies to each of your items. You can add standard and international pricing.<br><br>

- TAXES - Please use the Tax field to add the appropriate tax percentage for your state and country. We will pass these to you and is your responsibility to manage and report the appropriate taxes. <br><br>

- SOCIAL MARKETING – All your items are now shareable under our social affiliate program. Your products can be re-sold and you control the commission amounts with a minimum of 3% to the person enabling the sale. We'll do the rest of the work for you. <br><br>

- HAVE A PINTEREST ACCOUNT? - After you launch your store, Click on 'Selling Venue' on the left side, then go to the 'Tools' tab and with one click pin your entire store to Pinterest. <br><br><br><br>

Thank You - You are awesome! <br>

The Shopintoit team<br>

PS - Check our FAQs for any other questions you may have, or contact us at <a href="mailto:xxx@shopintoit.com">xxx@shopintoit.com</a> for whatever you need!<br>

Find us in Facebook - <a href="https://www.facebook.com/Shopintoit">https://www.facebook.com/Shopintoit</a><br>
Follow us in Twitter - <a href="https://twitter.com/shopintoit">https://twitter.com/shopintoit</a><br>
Pin & Share in Pinterest - <a href="http://www.pinterest.com/shopintoit/">http://www.pinterest.com/shopintoit/</a><br>
