<div id="container" class="row">
<div class="twelve columns">

                <h1>Upgrade <span class="gentium">Your</span> Browser</h1>

                <div class="row" style="text-align: left;">
                    <div class="panel seven columns centered">
                    <p>Hmmmm. It seems that your browser is either not up to date or you have Javascript turned off.</p>
                    <p>Shopinterest requires your browser have javascript turned on. Please check your browser settings or download the latest version of one of these popular browsers.<br>
                    <a href="http://www.google.com/chrome/">Chrome</a><br>
                    <a href="http://www.mozilla.org/">Firefox</a><br>
                    <a href="http://support.apple.com/downloads/#safari">Safari</a></p>
                    </div>
                </div>
	</div><!-- end content -->
</div>
</div><!-- end container -->
