<link rel="stylesheet" href="/v2/css/pages/dashboard.css">
<div id="dashboard" class="row page-layout dashboard">

    <section class="small-12 medium-12 large-9 columns">
        <div class="row">
            <div class="hide-for-iosapp small-3 medium-3 large-2 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/left_sidebar.phtml');?>
            </div>

            <div id="me-reseller" class="ios-small-12 small-9 medium-9 large-10 columns">
                <div class="hide-for-iosapp">
                    <? require_once(APPLICATION_PATH.'/views/scripts/partial/horizontal_subnav.phtml');?>
                </div>
                <!-- dashboard sub nav end -->

                <div class="hide-for-iosapp module-tools">
                    <div class="small-7 medium-7 large-7 columns">
                        <div class="module-tools-item">
                            <span class="dropdown module-dropdown" data-dropdown="status-dropdown">Status: <?=$this->status?></span>
                            <ul id="status-dropdown" class="f-dropdown module-dropdown-content" data-dropdown-content>
                                <li><a href="<?=url_append(array('status'=>'all'))?>">all</a></li>
                                <li><a href="<?=url_append(array('status'=>'pending'))?>">pending</a></li>
                                <li><a href="<?=url_append(array('status'=>'completed'))?>">completed</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="small-5 medium-5 large-5 columns">
                        <!--
                        <form action="" class="module-search glass-right" data-search>
                            <input type="text" class="search-input hidden">
                            <a href="javascript:;" class="search-submit"><i class="icon fi-magnifying-glass"></i></a>
                        </form>
                        -->
                        <div data-tooltip title="Earn money by sharing a product link with this aid appended, ex: http://www.shopintoit.com/marketplace/products/item?id=1&aid=<?=$this->user['aid']?>">
                            Your Affiliate ID: <?=$this->user['aid']?>
                        </div>
                    </div>
                </div>
                <!-- sorting header end -->
                <div id="tgt_datatable" style="margin-top: 10px;"><?=$this->datatable_view?></div>
            </div>
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
