<link rel="stylesheet" href="/v2/css/pages/dashboard.css">
<div id="dashboard" class="row page-layout dashboard">

    <section class="small-12 medium-12 large-9 columns">
        <div class="row">
            <div class="small-3 medium-3 large-2 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/left_sidebar.phtml');?>
            </div>
            <!-- side nav end -->

            <div id="payment-bank" class="small-9 medium-9 large-10 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/horizontal_subnav.phtml');?>

                <? require_once(APPLICATION_PATH.'/views/scripts/partial/horizontal_subnav2.phtml');?>
                <!-- dashboard nav end -->

                <form action="" data-abide="ajax" id="payment-bank-form" class="columns dashboard-form">
                    <div class="row">
                        <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
                        <div class="small-8 medium-8 large-8 columns alert-field"></div>
                    </div>
                    <div class="row field data-abide-input-container">
                        <div class="small-4 medium-4 large-4 columns">
                            <label for="bank-name" class="required">Bank Name</label>
                        </div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="text" id="bank-name" name="bank_name" value="<?=$this->user['bank_name']?>" required>
                            <small class="error">Bank Name is required.</small>
                        </div>
                    </div>
                    <div class="row field data-abide-input-container">
                        <div class="small-4 medium-4 large-4 columns">
                            <label for="routing-number" class="required">Routing Number</label>
                        </div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="text" id="routing-name" name="bank_routing_number" value="<?=$this->user['bank_routing_number']?>" required>
                            <small class="error">Routing Number is required.</small>
                        </div>
                    </div>
                    <div class="row field data-abide-input-container">
                        <div class="small-4 medium-4 large-4 columns">
                            <label for="account-number" class="required">Account Number</label>
                        </div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="text" id="account-number" name="bank_account_number" value="<?=$this->user['bank_account_number']?>" required>
                            <small class="error">Account Number is required.</small>
                        </div>
                    </div>
                    <div class="row field data-abide-input-container">
                        <div class="small-4 medium-4 large-4 columns">
                            <label for="re-account-number" class="required">Re-enter Account Number</label>
                        </div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="text" id="re-account-number" value="<?=$this->user['bank_account_number']?>" required data-equalto="account-number">
                            <small class="error">Account Number need to match.</small>
                        </div>
                    </div>
                    <div class="row field submit-field">
                        <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="submit" value="SAVE" id="submit-settings" class="submit-button">
                        </div8
                    </div>
                </form>
            </div>
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
