<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js lt-ie10" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />

        <!-- Set the viewport width to device width for mobile -->
        <meta name="viewport" content="width=device-width" />
        <title>Shutdown - Shopintoit</title>
        <!-- Included CSS Files -->
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"> <link rel="icon" href="/favicon.ico" type="image/x-icon"> <link rel="stylesheet" href="/v2/css/foundation.css"/>
        <link rel="stylesheet" href="/v2/css/foundation-icons.css">
        <link rel="stylesheet" href="/v2/css/common.css"/>
        <link rel="stylesheet" href="/v2/css/modules.css"/>
        <link rel="stylesheet" href="/css/simplePagination.css"/>
        <script src="/v2/js/modernizr.js"></script>
        <script src="/v2/js/jquery.js"></script>
        <script src="//www.google-analytics.com/cx/api.js"></script>
        <script src="/js/gat.js"></script>
        <script>
         setup_ga('xxx', 'shopintoit.com');
        </script>
    </head>

    <body>
        <div class="off-canvas-wrap" data-offcanvas>
            <div class="inner-wrap">
                <div id="fb-root"></div>
                <header id="header" class="hide-for-iosapp">
                    <div class="row header">
                        <div class="small-4 medium-5 large-4 columns">
                            <a class="logo">
                                <h1>
                                    <img src="/img/header-logo.png" data-interchange="[/img/header-logo@2x.png, (retina)]" alt="Shopintoit Logo">
                                    <span>Shopintoit</span>
                                </h1>
                            </a>
                        </div>

                    </div>
                </header>
                <!-- header end -->


                <div id="terms-page" class="row page-layout terms-page">

                    <section class="small-12 medium-12 large-9 columns page-layout-main">
                        <header class="module-header">
                            <h1 class="title">Shopintoit Closing on Sept. 10,  Thanks for all your support!</h1>
                        </header>
                        <div class="main">
                            <div class="large-12 columns">
                                <div class="term-item">
                                    <h4 class="title">Dear Shopintoit Storekeepers:</h4>
                                    <p class="spec">
                                        To much of our regret, we’d like to inform you that Shopintoit will be phasing out operations on September 10, 2014.  We are leaving a mission unrealized with a goal of providing you, our sellers, with a true social ecommerce and rewards platform that we wanted to build along with you.  We continue to believe the evolution of product discovery through friends via our multiple social platforms will be the way forward to expand sales, but we won’t be the ones leading the way.
                                        <br/><br/>
                                        You will have 30 days to prepare to migrate your store, Sales orders will stop on August 15th and by September 10 all stores and the site will be inoperative and no longer accessible.  Please request any refund requests from products bought but not delivered before August 31st. No requests can be processed after that.
                                        <br/><br/>
                                        We’d like to thank you for all your support during these last two years. After servicing over 5,000 independent retailers, posting over 100,000 different and unique products to social media generating millions of impressions to help sellers find traffic via their social networks. During these past 2 years, we have learned just how hard each one of our sellers works everyday, to make amazing jewelry, wonderful dresses, sparkling earrings, aromatic soaps, beautiful photos, stunning paintings and so much more to reach a buying audience.  And then spend hours in trying to generate traffic and sales. We were hoping to ease that process for all our members and regret we couldn't be more helpful.
                                        <br/><br/>
                                        Please note - Our billing terms will no longer apply as of today and no subscriptions have been charged. Your account information will not be sold to any third parties.  As a reminder, ShopIntoit did not keep any login information for any of your social accounts at any time.
                                        <br/><br/>
                                        For any questions, please contact us at xxx@shopinterest.co
                                        <br/><br/>
                                        Thanks!
                                        <br/><br/>
                                        The Shopintoit (ShopInterest) Team
                                    </p>
                                </div>
                            </div>
                        </div>
                    </section>

                </div>
            </div>
        </div>

        <!-- Included JS Files -->
        <script src="/js/jquery.simplePagination.js"></script>
        <script src="/v2/js/foundation/foundation.js"></script>
        <script src="/v2/js/foundation/foundation.offcanvas.js"></script>
        <script src="/v2/js/foundation/foundation.abide.js"></script>
        <script src="/v2/js/foundation/foundation.orbit.js"></script>
        <script src="/v2/js/foundation/foundation.reveal.js"></script>
        <script src="/v2/js/foundation/foundation.dropdown.js"></script>
        <script src="/v2/js/foundation/foundation.topbar.js"></script>
        <script src="/v2/js/foundation/foundation.tooltip.js"></script>
        <script src="/v2/js/foundation/foundation.interchange.js"></script>
        <script src="/js/jquery.reveal.js"></script>
        <script src="/js/jquery.placeholder.min.js"></script>
        <script src="/js/jquery.cookie.js"></script>
        <script src="/js/jquery.query.js"></script>
        <script src="/js/mustache.js"></script>
        <script src="/js/jquery.autocomplete.js"></script>
        <script src="/js/imagesloaded.min.js"></script>
        <script src="/js/libs/jquery-ui.js"></script>
        <script src="/js/app.js"></script>
        <script src="/js/index.combined.js"></script>
    </body>
</html>
