<div class="two columns"></div>
<div class="eight columns">

<div id="page"class="attached">
				
        <div id="hero" class="attached row">

                <h1>Login to <span class="gentium">start</span> Shopping</h1>

                <div class="row">
                    <div id="signup" class="panel five columns centered">
                            <form>
                              <div class="row">
                                <div class="twelve columns">  
                                    <input name="username" type="text" placeholder="Email" />
                                </div>
                              </div>
                              <div class="row"> 
                                <div class="twelve columns">   
                                    <input name="password" type="password" placeholder="Password" />
                                </div>
                              </div>
                              <div class="row">
                                    <button id="getstartedbutton" name="submit" type="submit" value="submit" class="button radius alert large" >Sign In</button>
                              </div>  
                            </form>
                    </div>
                    <div class="one column">&nbsp</div>
                </div>
        </div><!-- end hero -->
</div><!-- end page -->        