<div id="faqs-page" class="row page-layout faqs-page">

    <section class="small-12 medium-12 large-9 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">FAQs</h1>
        </header>
        <div class="main">
            <div class="large-12 columns">
                <h2 class="title">Account Setup</h2>
                <div class="faq-item">
                    <h3 class="title">What type of account do I need?</h3>
                    <p class="content">Your account can work as a <a href="#">Seller</a> and a <a href="#">Buyer</a> using the same credentials.<br>
                </div>
                <div class="faq-item">
                    <h3 class="title">Do I need a Pinterest account for ShopIntoit?</h3>
                    <p class="content">No, you only need the images of the items you wish to sell. You can also have your images on your Pinterest account and we can create a store from them as well. (add pinterest)</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">What is “Pinterest Name”?</h3>
                    <p class="content">Your Pinterest name is what your Pinterest account URL ends with as below. <br>
                    <a href="http://pinterest.com/accountname">http://pinterest.com/accountname</a><br>
                    It should not have spaces or special characters.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Can I change my ‘Pinterest Name’ on my account?</h3>
                    <p class="content">You can make changes on your account settings  page or request them manually via our feedback page.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Do I need a website to open an account at Shopintoit?</h3>
                    <p class="content">No, you don’t. All you need is the photos of the items you would like to sell, (with you or already at Pinterest) and a Paypal account. (You can create a paypal account if you don’t have one already) or you can connect your Etsy or Ebay store easily.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Can I open a store if I am not in the US?</h3>
                    <p class="content">Yes, we support the following currencies: Euro, British Pound, Canadian Dollar and Australian Dollar, if you can set your prices in these currencies, you can sell with Shopintoit within your own country or internationally.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Why do I need to provide a Credit Card or Paypal account when setting up an account?</h3>
                    <p class="content">We do this for security and fraud protection for the Shopintoit community. If you want the funds from your sales immediately available, you must have a credit card on file.  </p>
                </div>
                <div class="faq-item">
                    <h3 class="title">What Items are NOT allowed to sell at ShopIntoit?</h3>
                    <p class="content">ShopIntoit follows the local restrictions of each country as to what is available for sale. At a minimum,  adult items and merchandise, weapons, fresh fruit and vegetables, drugs and prescription-only pharmaceuticals, and any illegal items as per the local ordinances of the seller and buyer are forbidden to be sold at ShopIntoit.</p>
                </div>

                <h2 class="title">Sales Setup</h2>
                <div class="faq-item">
                    <h3 class="title">What do I need to open an account at Shopintoit?</h3>
                    <p class="content">Any one with items to sell can create an account at Shopintoit. All you need are some photos of the items that you wish to sell. Or have those images ready on your Pinterest account. Also, you will need a payment method. We support Paypal for now.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">What if I do have a Pinterest account?</h3>
                    <p class="content">Add your Pinterest account info in your profile,  then you will be able to import your images from there or any other social media account that you have. You can import those images to create items for sale.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">What information do I need to provide on my items?</h3>
                    <p class="content">We will ask you the following information for your items:<br/>
                        <b>Title</b>– You can re-use the title of your Pinned image or re-write it. This title is displayed below the image and used in the shopping cart and receipt.<br/>
                        <b>Sale Price</b> – Your item sales price before taxes.<br/>
                        <b>Standard Shipping Price</b>– this is the most common cost that you item have. You have the option to offer international & domestic. We also have express and priority shipping available.<br/>
                        <b>Commission</b> – The final commission given to the person who helps you close the sale, it starts at a 3% mandatory minimum and can be increased.<br/>
                        <b>Description</b> – The description can also be re-used or re-written, and will be visible when a customer clicks on the Pin prior to purchase.<br/>
                        <b>Size</b> – If you are selling clothes, we are giving you the option to specify a size. If those sizes don’t describe your item accurately, write the details in the description.<br/>
                        <b>Start Date-End Date</b> – If you want to sell your item for a specific period of time, add these optional values. If not entered, the item will be on sale for as long as it is in Stock.<br/></p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How do I fulfill orders?</h3>
                    <p class="content">Each order is recorded in your Shopintoit store dashboard. You will see the items ordered and the address of the buyer. You can see all your orders on your seller dashboard.</p>
                </div>

                <h2 class="title">Marketing</h2>
                <div class="faq-item">
                    <h3 class="title">How can I market my store in social media?</h3>
                    <p class="content">There are many ways to market your store:<br/>
                        <b>Pin your ‘store’ page to your Pinterest page.</b> We recommend making the store your Board cover. Remember that your followers will have to click to go to Shopintoit.com to complete the purchase.<br/>
                        <b>Share your store and each of your best products</b> via Facebook and Twitter on a regular basis.<br/>
                        <b>Add your links in your blog, newsletter and other places</b> – Remember the store and each product can be linked anywhere.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Does Shopintoit replace the links on the Pins in the boards I pick?</h3>
                    <p class="content">No, we don’t. Your pins remain unchanged in your Pinterest account. We do recommend that you change the URL to your store front. We’ll add unique URLs to each of your Pins later on.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Does Shopintoit offer  discount codes or promotional codes for my shoppers?</h3>
                    <p class="content">Yes, you can create specific coupons that apply to an item, or to your entire store. You can give a % off the price, dollars off the price or offer free shipping.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How can I be a ‘Featured Store’ in the home page?</h3>
                    <p class="content">We select featured stores based on quality of merchandise, user feedback and existing partnerships. Product placement in the home page and other pages is available for a fee. See pricing page for details.</p>
                </div>
                <h2 class="title">Payments and Fees</h2>
                <div class="faq-item">
                    <h3 class="title">If you want to sell via Shopintoit:</h3>
                    <p class="content">We don’t take ownership of the items you sell. You can sell your own items or re-sell items from other sellers</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Is Shopintoit free?</h3>
                    <p class="content">See <a href="/pricing">pricing</a> page for more information on paypal, disbursement and sales fees. </p>
                </div>
                <div class="faq-item">
                    <h3 class="title">What are my protections as a seller/buyer?</h3>
                    <p class="content">As a seller, you have the protections offered by the payment method you choose. Shopintoit is not liable or responsible for the successful completion of the transaction<br>
                        As a reseller, we pay commissions to re-sellers every 30 days, so that any cancellations and issues can be deducted as needed. <br>
                        Shopintoit will request proof of shipment in case of a dispute and a refund request has not been completed from the seller to the buyer.<br>
                        Shopintoit will contact sellers as a last resort if a buyer has requested a refund if none has been received. After 7 days without answer, Shopintoit will refund the payment to the buyer and subtract the amount or bill the difference to seller.</p>
                </div>
                <h2 class="title">Learning Pinterest</h2>
                <div class="faq-item">
                    <h3 class="title">What do these Terms mean?</h3>
                    <p class="content">
                        <b>Followers</b> – The number of followers of your account or your board. Remember people can choose to do either.<br/>
                        <b>Following</b> – The number of Pinterest users your account is following.<br/>
                        <b>Re-pins</b> – The number of times a pin you have in any of your boards has been repined in other’s boards.<br/>
                        <b>Likes</b> – The number of times a pin you have in any of your boards has been ‘Liked’.<br/>
                        <b>Public</b> Board – A board where any user can pin an image.<br/>
                        <b>Comment</b> – Any note any user can leave on your product images at Pinterest.</p>
                </div>
                <h2 class="title">Shopintoit Affiliate Program</h2>
                <div class="faq-item">
                    <h3 class="title">What is the Shopintoit Affiliate Program?</h3>
                    <p class="content">The Shopintoit Affiliate Program is the easiest way to make your Shopintoit Store products available for selling via sharing. Your products can be sold beyond your Shopintoit store and you determine how much of a commission you are willing to pay, starting with a minimum of 5%.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How Does the Shopintoit affiliate program work?</h3>
                    <p class="content">All your products are eligible for an affiliate reward. Each product listed has a 5% minimum ‘commission payment’ that is given to whoever helped you sell the item. You can set the commission higher if you wish to do so. After that, Shopintoit makes those products available with tracking so that any affiliate network, or third party can display your items on their websites, and once a sale happens, we will take care of the payments for everyone.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Do I require a deposit to sell via the Shopintoit?</h3>
                    <p class="content">No deposit is required since we manage the payments ourselves. However, we do request that you MUST have a detailed return policy on your store profile.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Do I need to change any of my payments to pay commissions?</h3>
                    <p class="content">No, we'll continue using your PayPal account and will deposit to your account the sales you generate and S&H charges minus the affiliate fee and any of our fees.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Can I sell other's Shopintoit's products on my site/store/blog?</h3>
                    <p class="content">Yes! You can also be a third-party seller and join the Shopintoit Affiliate Program as a reseller. This is a great way to help other sellers and give your store related products and items that might complement a sale. You get paid and the seller gets a sale, so everyone wins.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How much are the costs to sell at Shopintoit:</h3>
                        STORE PLAN:<br>
                        1) Paypal payment Fees  <br>
                        2) Paypal disbursement fees <br>
                        3) 5% Transaction fee <br>
                        4) 5% Affiliate fee <br>
                </div>
                <div class="faq-item">
                    <h3 class="title">What is the commission paid?</h3>
                    <p class="content">You determine the percentage that you are willing to pay for a sale and different items can have different rates for more flexibility. The minimum is 5% per product, and this is paid to the person who shared any product that was purchased.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">Where are my products sold?</h3>
                    <p class="content">We will limit our affiliates and third party sellers to the US and countries supported by our currencies managed.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">What happens if a product is cancelled or returned?</h3>
                    <p class="content">If one of your products is cancelled or returned in accordance to your own return policy and no later than 30 days after purchase, you get the affiliate fee returned to you (minus any payment fees).</p>
                </div>

                <h2>Shopintoit Affiliate Program - for Third Party Sellers and Affiliate Networks</h2>
                <div class="faq-item">
                    <h3 class="title">What is the Shopintoit Affiliate Program?</h3>
                    <p class="content">The Shopintoit Affiliate Program is the easiest way to make your Shopintoit Store products available for selling via affiliates. Anyone can share all of your Shopintoit products available. You can now expand the products you offer with unique products and gifts that can't be found anywhere else.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How Does the Shopintoit Affiliate Program work?</h3>
                    <p class="content">Our sellers have made all products available for affiliate sales. If you share items, or anyone, we will provide you with trackable links so that any of the sales you help complete to the site generate a commission.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">What are the requirements?</h3>
                    <p class="content">Your completed profile registration, agree with the terms and conditions, and a Paypal account that we can use to deposit your earnings.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How much is the cost to enroll?</h3>
                    <p class="content">There is no cost to join the Affiliate Program as a reseller.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How do you track the sales?</h3>
                    <p class="content">The main method of tracking is via URL links. All the items you select will have your affiliate ID in the URL. This is how we track the sales generated. Only items available for affiliates with a trackable URL are eligible for payments. We may also use cookies to track visits for 90 days. Items not listed as available for commissions do not generate commissions for you.</p>
                </div>
                <div class="faq-item">
                    <h3 class="title">When is the commission paid?</h3>
                    <p class="content">Commissions are paid 30 days after each sale on the Friday immediately following 30 days after the purchase. Commissions are not paid in case of returns. </p>
                </div>
                <div class="faq-item">
                    <h3 class="title">How do re-sellers collect their commissions?</h3>
                    <p class="content">Commissions will be deposited to your paypal account. Paypal disbursement fees will apply.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- pricing plan end -->

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
