<style>
    .bullets li {
        font-size: 17px;margin-left: -11px;
    }
</style>

<link rel="stylesheet" href="/css/cart.css"/>
<div id="container" class="row page-layout">
    <section class="small-12 medium-12 large-12 columns page-layout-main">
        <div class="large-12 columns" id="feature">
            <div class="small-12 medium-6 large-6 columns mobile-four" style="padding-bottom: 20px;background-color:#f73837">
                <h2 style="font-size:2.15rem; color: white">
                    Create your<span class="gentium"> FREE ShopIntoit</span> <br>Social Store<br>Sell More Now!
                </h2>
                <ul style="font-size:1.25rem;margin-left:1.5rem; color: white">
                    <li>Save $100's of dollars vs. Shopify, Ebay or Etsy</li>
                    <li>Turn your followers into loyal customers</li>
                    <li>Create an amazing store in just minutes</li>
                    <li>Turn Twitter, Pinterest, Facebook into new sales channels</li>
                </ul>
                <div class="columns mobile-four text-center">
                    <a class="button large success radius startfree" style="font-size: 200%;">SIGN UP NOW!</a>
                </div>
            </div>

            <div class="small-12 medium-6 large-6 columns" style="text-align: center;">
                <iframe width="500" height="305" src="//www.youtube.com/embed/yxpNe9-qpk4" frameborder="0" allowfullscreen></iframe>
            </div>

            <div class="large-12 columns">
                <div class="storename home">
                    <h3>As seen on</h3>
                    <p style="font-size:1rem;">
                        <a target="_blank" href="http://techcrunch.com/2012/09/25/shopinterest-the-startup-that-lets-you-sell-from-your-pinterest-boards-gets-500-startups-backing/">
                            <img src="/v2/img/techcrunch-hover.png" alt="" width="260" />
                        </a>
                        <a target="_blank" href="http://www.huffingtonpost.com/2012/09/25/shopinterest-e-commerce-pinterest-backing-500-startups_n_1913015.html">
                            <img src="/v2/img/huffingtonpost-hover.png" alt="" width="260" />
                        </a>
                        <a target="_blank" href="https://www.facebook.com/Shopintoit">
                            <img src="/v2/img/facebook-hover.png" width="260">
                        </a>
                        <a target="_blank" href="http://www.pinterest.com/shopintoit/">
                            <img src="/v2/img/pinterest-hover.png" width="260">
                        </a>
                    </p>
                </div>
            </div>

            <div class="large-12 columns">
                <h3>Available In...</h3>
                <p>United States, Canada, UK, European Union, Australia</p>
            </div>
        </div>
    </section>
</div><!-- end container -->
