<div id="how-page" class="row page-layout how-page">

    <section class="small-4 medium-4 large-2 columns page-layout-main">
        <ul class="side-nav">
            <li><a href="/how/topics">Help Topics</a></li>
            <li><a href="/how" class="active">Help Videos</a></li>
        </ul>
    </section>
    
    <section class="small-8 medium-8 large-7 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">How It Works</h1>
        </header>
        <div class="main">
            <div class="large-12 columns text-center">
                <h3 class="title">How It Works</h3>
                <div class="video">
                    <center>
                        <iframe width="640" height="360" src="//www.youtube.com/embed/yxpNe9-qpk4" frameborder="0" allowfullscreen></iframe>
                    </center>
                </div>
            </div>
        </div>
    </section>
    <!-- pricing plan end -->

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
