<div id="how-page" class="row page-layout how-page">

    <section class="small-4 medium-4 large-2 columns page-layout-main">
        <ul class="side-nav">
            <li><a href="/how/topics" class="active">Help Topics</a></li>
            <li><a href="/how">Help Videos</a></li>
        </ul>
    </section>
    
    <section class="small-8 medium-8 large-7 columns page-layout-main">
        <header class="module-header">
            <h1 class="title">Help Topics</h1>
        </header>
        <div class="main">
            <div class="large-12 columns text-center">
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/signing-up/" target="_blank">How to Signup</a></h3>
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/how-to-reset-your-password/" target="_blank">How to Reset your password</a></h3>
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/how-to-add-products/" target="_blank">How to Add Products</a></h3>
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/how-to-create-coupons/" target="_blank">How to Create Coupons</a></h3>
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/how-to-contact-your-customers/" target="_blank">How to Contact Your Customers</a></h3>
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/tips-to-make-sharp-pictures/" target="_blank">How to Make Sharp Pictures</a></h3>
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/tips-to-get-better-sales/" target="_blank">Tips to Make Better Sales</a></h3>
                <h3 class="title"><a href="http://community.shopinterest.co/forums/topic/how-to-promote-your-shopitnerest-store/" target="_blank">How to Promote your Shopintoit Store</a></h3>
                <h3 class="title">Still need help, <a href="/ticket">Contact Us ...</a></h3>
            </div>
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
