<link href='http://fonts.googleapis.com/css?family=Rokkitt' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/v2/css/pages/landing.css">
<div id="landing-page" class="page-layout landing-page">
    <div class="row landing-item landing-one text-center">
        <div class="large-12 columns landing-item-content">
            <p class="intro">Introducing our new store service.</p>
            <h2 class="title">ShopBuilder</h2>
            <p>Let us build the store you want - We'll do it for you!<br>Just <a href="">contact us</a> for more details.</p>
            <a href="javascript:;" class="try-it">I Wanna Try It Now</a>
        </div>
        <a href="javascript:;" class="more">Explore More<br><span class="arrow">&#9002;</span></a>
        <div class="cover"></div>
    </div>

    <div class="row landing-item landing-two text-center">
        <div class="large-12 columns landing-item-content">
            <h2 class="title">Feel limited by the default page?</h2>
            <p><strong>ShopBuilder</strong>  can create the perfect store for all your needs.</p>
        </div>
        <div class="landing-item-image center-bottom" style="width:100%;">
            <div class="medium-3 large-3 columns">&nbsp;</div>
            <div class="medium-6 large-6 columns browser">
                <img src="/v2/img/landing-two-image.jpg">
                <i class="fi-arrows-expand"></i>
                <div class="buttons">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="medium-3 large-3 columns">&nbsp;</div>
        </div>
        <a href="javascript:;" class="try-it top-right">Try Now</a>
        <a href="javascript:;" class="more"><span class="arrow">&#9002;</span></a>
        <div class="cover"></div>
    </div>

    <div class="row landing-item landing-three">
        <div class="medium-5 large-5 columns landing-item-content">
            <h2 class="title">Want to have a fully customized store page?</h2>
            <p><strong>ShopBuilder</strong> is your choice.</p>
        </div>
        <div class="medium-7 large-7 columns landing-item-image right-center">
            <div class="browser">
                <img src="/v2/img/landing-three-image.jpg">
                <i class="fi-arrows-expand"></i>
                <div class="buttons">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
        <a href="javascript:;" class="try-it bottom-left">Try Now</a>
        <a href="javascript:;" class="more"><span class="arrow">&#9002;</span></a>
        <div class="cover"></div>
    </div>

    <div class="row landing-item landing-four">
        <div class="medium-5 large-5 columns landing-item-content">
            <h2 class="title">Don't have design resources?</h2>
            <p><strong>ShopBuilder</strong> team will do all for you.</p>
        </div>
        <div class="medium-7 large-7 columns landing-item-image left-center">
            <div class="browser">
                <img src="/v2/img/landing-four-image.jpg">
                <i class="fi-arrows-expand"></i>
                <div class="buttons">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
        <a href="javascript:;" class="try-it bottom-right">Try Now</a>
        <a href="javascript:;" class="more"><span class="arrow">&#9002;</span></a>
        <div class="cover"></div>
    </div>

    <div class="row landing-item landing-five text-center">
        <div class="large-12 columns landing-item-content">
            <h2 class="title">Want to be unique among thousands of stores?</h2>
            <p><strong>ShopBuilder</strong> team will make an exclusive page for you only.</p>
        </div>
        <div class="landing-item-image center-top" style="width:100%;">
            <div class="medium-3 large-3 columns">&nbsp;</div>
            <div class="medium-6 large-6 columns browser hide-browser">
                <img src="/v2/img/landing-five-image.jpg">
                <i class="fi-arrows-expand"></i>
                <div class="buttons">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="medium-3 large-3 columns">&nbsp;</div>
        </div>
        <a href="javascript:;" class="try-it top-right">Try Now</a>
        <a href="javascript:;" class="more"><span class="arrow">&#9002;</span></a>
        <div class="cover"></div>
    </div>

    <div class="row landing-item landing-last text-center">
        <div class="large-12 columns landing-item-content">
            <h2 class="title">Talk to us.</h2>
            <p>We'd like to hear from you.</p>
            <p class=" alert-field"></p>
            <div class="medium-3 large-3 columns">&nbsp;</div>
            <form class="medium-6 large-6 columns contact-form" data-abide="ajax">
                <input type="hidden" name="type" value="shopbuilder">
                <div class="medium-6 large-6 columns data-abide-input-container">
                    <input type="text" name="name" placeholder="Name" required>
                    <input type="email" name="email" placeholder="Email" required>
                    <input type="text" name="subject" placeholder="Subject" required>
                    <small class="error">All above fields are required.</small>
                </div>
                <div class="medium-6 large-6 columns data-abide-input-container">
                    <textarea id="message" name="text"
                              placeholder="Write your message here. Keep it simple, concise and intriguing :)" required></textarea>
                    <small class="error">Message is required.</small>
                </div>
                <div class="columns">
                    <input type="submit" class="button" value="Submit Your Message">
                </div>
            </form>
            <div class="medium-3 large-3 columns">&nbsp;</div>
        </div>
        <div class="cover"></div>
    </div>

</div>
