<? $this->placeholder("extra_header")->captureStart();?>
<link rel="stylesheet" href="/css/cart.css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<? $this->placeholder("extra_header")->captureEnd();?>
<div class="main row">

    <div class="row">
        <div class="twelve comlumns">
            <? require_once(APPLICATION_PATH.'/views/scripts/partial/subnav.phtml');?>
            <h1>ADD A COUPON</h1> 
        </div>
    </div>
    <div class="row panel">
        <div class="twelve columns">
            <div class="row">
                <div class="three columns" style="padding: 0px; padding-top: 8px; font-size: 16px;">
                    <?= $this->page_used_by === 'admin' ? 'Store URL Or Product Item URL' : 'Product Item URL'; ?>
                </div>
                <div class="nine columns" style="padding-right: 0px">
                    <div class="row collapse">
                        <div class="ten mobile-three columns">
                            <input type="text" name='input_url' id='input_url' value="<?= default2String($_REQUEST['input_url'])?>" placeholder='URL' />
                        </div>
                        <div class="two mobile-one columns">
                            <a id='search_btn' class="button expand postfix search_btn green">Next</a>
                        </div>
                    </div>          
                </div>
            </div> 
            
            <div class="row" style="margin: 20px 0;">
                <hr/>
            </div>        

            <div class="row">
                <?if(!empty($this->errnos)){ ?>
                <?foreach ($this->errnos as $key => $value){ ?>
                <div class="alert-box alert">
                    <?= $this->errors[$key]['msg']; ?>
                    <a href="" class="close">&times;</a>
                </div>
                <? } ?>
                <?}?>
                <?if($this->create_ok == true){ ?>
                <div class="alert-box success">
                    Coupon was created.
                    <a href="" class="close">&times;</a>
                </div>
                <?}?>
            </div>    
            
            <div class="row"> 
                <form action="#" method='post'>
                    <input type="hidden" name='input_url' id='input_url_hidden' value="<?= default2String($_REQUEST['input_url']); ?>" placeholder='URL' />

                    <div class="row">
                        <div class="six column" style="border-bottom-left-radius: ">
                            <div class="row" style="margin-bottom: 10px;">
                                <?if($this->page_used_by === 'admin'){?>
                                <div class="six column">
                                    <div class="row">
                                        <div class="four columns">
                                            <label class="left inline">Store Id :</label>
                                        </div>
                                        <div class="eight columns">
                                            <label class="left inline store_id_label"><?=default2String($_REQUEST['store_id']);?></label>
                                            <input type="hidden" name='store_id' id='store_id' value="<?=default2String($_REQUEST['store_id']);?>"/>
                                        </div>                                   
                                    </div>
                                </div>
                                <?}?>
                                <div class="six column">
                                    <div class="row">
                                        <div class="five columns">
                                            <label class="left inline">Product Id :</label>
                                        </div>
                                        <div class="seven columns">   
                                            <label class="left inline product_id_label"><?=default2String($_REQUEST['product_id']);?></label>
                                            <input type="hidden" name='product_id' id='product_id' value="<?=default2String($_REQUEST['product_id']);?>"/>
                                        </div>                                   
                                    </div>
                                </div>  
                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Scope:</label>
                                </div>
                                <div class="eight columns">
                                    <select class='seven' id='scope' name='scope' style="border-color: #848484 #c1c1c1 #e1e1e1; height: 2.5em; width: 320px;">
                                        <!-- 
                                        
                                        -->
                                        <?if($this->page_used_by === 'admin'){?>
                                        <option value='1' <?php if (default2String($_REQUEST['scope']) == 1) echo 'selected' ?>>Site</option>
                                        <?}?>
                                        <option value='2' <?php if (default2String($_REQUEST['scope']) == 2) echo 'selected' ?>>Store</option>
                                        <option value='3' <?php if (default2String($_REQUEST['scope']) == 3) echo 'selected' ?>>Product</option>
                                    </select>
                                </div>

                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Start Time:</label>
                                </div>
                                <div class="eight columns">
                                    <input type="text" id="start_time" name='start_time' value="<?if(!empty2(strtotime2(default2String($_REQUEST['start_time'])))) {echo strftime('%F', strtotime2(default2String($_REQUEST['start_time'])));}?>"/>
                                </div>

                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">End Time:</label>
                                </div>
                                <div class="eight columns">
                                    <input type="text" id="end_time" name='end_time' value="<?if(!empty2(strtotime2(default2String($_REQUEST['end_time'])))) {echo strftime('%F', strtotime2(default2String($_REQUEST['end_time'])));}?>"/>
                                </div>

                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Price Offer Type:</label>
                                </div>
                                <div class="eight columns">
                                    <select id='price_offer_type' name='price_offer_type' style="border-color: #848484 #c1c1c1 #e1e1e1; height: 2.5em; width: 320px;">
                                        <option value='1' <?php if (default2String($_REQUEST['price_offer_type']) == 1) echo 'selected' ?>>Percentage_off</option> 
                                        <option value='2' <?php if (default2String($_REQUEST['price_offer_type']) == 2) echo 'selected' ?>>Flat_value_off</option>
                                        <!-- 
                                        <option value='3'>Bundle</option>
                                        -->
                                    </select>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Price Offer Value:</label>
                                </div>
                                <div class="eight columns">
                                    <input type='text' id='price_off' name='price_off' value="<?= default2String($_REQUEST['price_off']); ?>"/>
                                </div>

                            </div>
                        </div>
                        
                        <div class="one column" style="height: 250px;width: 0px;padding: 0;border: solid 1px #e6e6e6; margin-left: 40px;"></div>                
                        <div class="five column">
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Offer Name:</label>
                                </div>
                                <div class="eight columns">
                                    <input type="text" id="offer_name" name='offer_name' value="<?= default2String($_REQUEST['offer_name']); ?>"/>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Offer Description:</label>
                                </div>
                                <div class="eight columns">
                                    <textarea rows="4" cols="50" style="height: 130px;" id='offer_description' name='offer_description'><?= default2String($_REQUEST['offer_description']) ?></textarea>                            
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Usage Limit:</label>
                                </div>
                                <div class="eight columns">
                                    <input type="text" id="usage_limit" name='usage_limit' value="<?= default2String($_REQUEST['usage_limit']); ?>"/>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="four columns">
                                    <label class="left inline">Usage Restriction:</label>
                                </div>
                                <div class="eight columns">
                                    <input type="text" id='usage_restriction' name='usage_restriction' value="<?= default2String($_REQUEST['usage_restriction']); ?>"/>
                                </div>
                            </div>
                        </div>     
                    </div> 

                    <div class="row" style="margin-top: 20px;">
                        <div class="three columns centered">
                            <i>Is Sale : </i> <input type="checkbox" class="is_sale" name="is_sale" <?php if (isset($_REQUEST['is_sale'])) echo 'checked'; ?>>
                            <i>Free Shipping : </i> <input type="checkbox" class="free_shipping" name="free_shipping" <?php if (isset($_REQUEST['free_shipping'])) echo 'checked'; ?>>
                        </div>
                    </div>

                    <div class="row" style="margin: 20px 0;">
                        <hr/>
                    </div>              
                    
                    <div class="row">
                        <div class="six columns">
                            <label class="left inline">Coupon Code:</label>
                            <label class="left inline"><?=default2String($_REQUEST['code'], $this->coupon_code); ?></label>
                            <input type="hidden" id="code" value="<?=default2String($_REQUEST['code'], $this->coupon_code); ?>" name='code'/>     
                        </div>            
                    </div>

                    <div class="row">
                        <div class=" two columns centered">
                            <input type='submit' name='submit' value='Save Coupon' class="radius alert button" style="margin-top:5px;" />
                        </div>
                    </div>
                </form> 
            </div> 
        </div>
    </div>            

    <div class="row">
        <div class="twelve comlumns">
            <h1>EDIT COUPON CODES</h1> 
        </div>
    </div>
    <?if(!empty($this->coupons)){?>
    <div class="row">
        <div class='twelve columns' style="padding:0;">
            <table>
                <thead>
                    <tr>
                        <th>Code</th>
                        <th>Scope</th>
                        <th>Start Time</th> 
                        <th>End Time</th>                     
                        <th>Price Offer Type</th>
                        <th>Price Off</th>
                        <th>Offer Name</th>                    
                        <th>Offer Description</th>
                        <th>Usage Limit</th> 
                        <th>Usage Restriction</th>
                        <th>Is Sale</th>
                        <th>Free Sipping</th>
                        <th>Operator</th>
                    </tr>
                </thead>
                <tbody>
                    <?foreach($this->coupons as $coupon){?>
                    <tr>
                        <td><?= $coupon['code'] ?></td>
                        <td><a target ="_blank" <?php if ($coupon['scope'] === 'Store'){echo "href={$coupon['store_url']}";} else if ($coupon['scope'] === 'Product') {echo "href={$coupon['product_url']}";} ?> ><?= $coupon['scope'] ?></a></td>
                        <td><?$a = explode(' ', $coupon['start_time']); echo $a[0];?></td>
                        <td><?$a = explode(' ', $coupon['end_time']); echo $a[0];?></td>                    
                        <td><?= $coupon['price_offer_type'] ?></td>
                        <td><?= $coupon['price_off'] ?></td>
                        <td><?= $coupon['offer_name'] ?></td>
                        <td><?= $coupon['offer_description'] ?></td>    
                        <td><?= $coupon['usage_limit'] ?></td> 
                        <td><?= $coupon['usage_restriction'] ?></td>        
                        <td><?= $coupon['is_sale'] ?></td>
                        <td><?= $coupon['free_shipping'] ?></td>
                        <td>
                            <a class="button alert radius small delete" code="<?= $coupon['code'] ?>" style="margin-bottom:5px;">Delete</a>
                            <a href="<?='?coupon_id='.$coupon['coupon_id']?>" class="button blue radius small edit" style="padding-left: 20px; padding-right: 20px;">Edit</a>                       </td>   
                    </tr>
                    <?}?>
                </tbody>
            </table>
        </div>
    </div>    
    <?}?>
</div>

</div>
