<div class="row social_channels">
    <div class="five columns">
        <div class="fb-like" data-href="http://www.shopinterest.co" data-send="true" data-width="450" data-show-faces="false"></div>
    </div>
    <div class="three columns">
        <a href="https://twitter.com/shopintoit" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @shopinterest</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
    <div class="three columns">
        <div class="fb-subscribe" data-href="https://www.facebook.com/shopintoit" data-show-faces="false" data-width="450"></div>
    </div>
    <div class="one columns"></div>
</div>
