<link rel="stylesheet" type="text/css" href="/css/cart.css"/>
<link rel="stylesheet" type="text/css" href="/css/app.css"/>

<div class="main row">

    <div class="twelve columns" id="cart">
        <div class="storename">
            <h1>OneMark Creations</h1>
        </div>
        <div class="row">
            <div class="nine columns centered">
                <div id="productdetail">
                  <ul class="cart_list01_content">
                  	<li>
                  		<span class="imgholder">
                  			<img alt="" src="//ny-image3.etsy.com/000/0/6077475/il_fullxfull.204499447.jpg">
                  			<class class="cart_list01_price">$9.95</class>
                  		</span>
                  	</li>
                  	<li class="add">
                  		 <a class="button medium alert radius cart" href="">Add to Cart</a>
                                 <a target="_blank" class="button medium alert radius pin" href="http://pinterest.com/pin/create/button/?url=http://onemarkcreations.shopinterest.co/products/item?id=26&amp;media=https://ny-image3.etsy.com/000/0/6077475/il_fullxfull.204499447.jpg&amp;description=Tea Bag Travel Wallet - Skulls on Pink, $9.95">Pin</a>
                                 <!-- AddThis Button BEGIN -->
                                 <!--<div class="addthis_toolbox addthis_32x32_style addthis_default_style" style="display:inline; float:right;">
                                 	<a class="addthis_button_facebook"></a>
                                 	<a class="addthis_button_twitter"></a>
                                 	<a class="addthis_button_email"></a>
                                 </div>
                                 <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
                                 <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=thenooch"></script>-->
                                 <!-- AddThis Button END -->


                  	</li>

                	<li>
                                <p class="product_name">Tea Bag Travel Wallet - Skulls on Pink</p>
                  		<p>This fun, funky fabric features brown skulls and cross bones on a background of pretty pink.

A cup of your favorite tea is the perfect break in your day. No matter where your day takes you - always have your favorite tea bags close at hand and ready to enjoy with this pretty Tea Bag Wallet.

Made of the finest 100% cotton fabrics - it's size and design allow it to comfortably hold 5 - 6 of your favorite teabags and a few packets of your favorite sweetener as well. Tuck it into your purse, bag, pack or briefcase and you are ready to go. This Tea Bag Wallet comes to you packaged in a pretty gift box and includes a selection of premium tea bags - perfect for that hostess or thank you gift.

This Tea Bag Wallet is handcrafted in Beaverton, Oregon and is an original design of OneMark Creations - &copy; 2006. All rights reserved.

If you love this Tea Bag Wallet and would like more than I have listed - just let me know and I can increase the quantity available.</p>
                  	</li>
                  	<li>
                  	  	<p class="shipping_info">
                                                                        Shipping:
                                    <span class="shipping">$
                                        3.95                                    </span> <i>+
                                    <span class="additional_shipping">$
                                        0                                    </span> for each addition Tea Bag Travel Wallet - Skulls on Pink</i>
                                                                    </p>
                  	</li>
                  </ul>
                </div>

            </div>
             <div class="row"><div class="nine columns centered"><h5><a href="/">« View more products from OneMark Creations</a></h5></div></div>

        </div>
    </div>
</div>
