<div id="container" class="row">
    <div class="twelve columns">
        <?php if ($this->status === 'success') { ?>
            <!-- SHOW IF SUCCESS --><h1>Thank <span class="gentium">You</span></h1><!-- SHOW IF SUCCESS -->
        <?php } ?>
        <?php if ($this->status === 'failure') { ?>
            <!-- SHOW IF FAIL --><h1>Payment <span class="gentium">Unsuccesful</span></h1><!-- SHOW IF FAIL -->
            <? }?>
            <div class="row">
                <div class="panel ten columns centered">
                    <?php if ($this->status === 'success') { ?>
                        <!-- SHOW IF SUCCESS --><h5>Your payment was successfully received.</h5>
                        <p>Thank you for shopping with us. Your order will ship shortly.</p><!-- SHOW IF SUCCESS -->
                    <?php } ?>
                    <?php if ($this->status === 'failure') { ?>
                        <h5><?= $this->errors[$errno]['msg']; ?></h5>
                        <!--<p>Please try again by <a href="<?= $this->retry_link; ?>">clicking here</a>.</p>-->
                        <? }?>
                        <p>Continue shopping at 
                            <a href="<?= $this->store_url ?>"><?= $this->store_name; ?></a></p> or 
                        <a href="<?= getSiteMerchantUrl(); ?>/flashdeals">Shopinterest Flash Sales</a>
            </div>
        </div>
    </div>  
</div>