<div id="container" class="row">
<div class="twelve columns">
<? require_once(APPLICATION_PATH.'/views/scripts/partial/subnav.phtml');?>
    <h1>Confirm <span class="gentium">and</span> Pay</h1>
    <div class="row">
                    <div class="panel ten columns centered">
                      <div class="row">
                      <div class="alert-box">
                      Double check your payment details then click "Pay Now" to complete your purchase.
                      </div>
                        <div class="eight columns">
                            <table>
                            <tr>
								<th class="product">Product</th>
								<th class="price">Price</th>
								<th class="quantity">Quantity</th>
								<th class="total">Total</th>
                            </tr>
                            <tr>
								<td class="product"><div class="item"><img src="//media-cache-ec2.pinterest.com/upload/27936460159134234_pWiggVBK_b.jpg"></div>
								Turtle shaped ice cream scoop that has a really long title</td>
								<td class="price">$10.00</td>
								<td class="quantity">2</td>
								<td class="total">$20.00</td>
                            </tr>
							<tr>
								<td class="product"><div class="item"><img src="//media-cache-ec2.pinterest.com/upload/27936460159134234_pWiggVBK_b.jpg"></div>one pencil, black</td>
								<td class="price">$10.00</td>
								<td class="quantity">2</td>
								<td class="total">$20.00</td>
							</tr>
                            <tr class="method">
                            	<td></td>
                            	<td></td>
                            	<td class="details">
                            		<p>Subtotal</p>
                            		<p>Shipping</p>
                            		<p>Total</p>
                            	</td>
                            	<td class="total">
                            		<p>$55.00</p>
                            		<p>$10.00</p>
                            		<p>$65.00</p>
                            	</td>
                            </tr>

                            </table>
                            <a href="" class="button radius alert large">Pay Now</a>
                        </div>
                        <div class="one columns"></div>
                        <div class="three columns userdetails">
	                        <h6>Payment Method</h6>
	                        <p>Paypal</p>
	                        <h6>Shipping Method</h6>
	                        <p>Standard Ground</p>
							<h6>Ship To</h6>
							<p>Nate Jackson</p>
							<p>3454 Green Aveenue</p>
							<p>San Francisco, CA 94102</p>
							<p>United States</p>
                        </div>
                      </div>
                    </div>
                </div>
</div>
</div><!-- end container -->
