<link rel="stylesheet" href="/v2/css/pages/dashboard.css">
<div id="dashboard" class="row page-layout dashboard">
    <section class="small-12 medium-12 large-9 columns">
        <div class="row">
            <div class="small-3 medium-3 large-2 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/left_sidebar.phtml');?>
            </div>
            <!-- side nav end -->

            <div id="sellingvenue-products-reseller" class="small-9 medium-9 large-10 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/horizontal_subnav.phtml');?>
                <!-- dashboard sub nav end -->

                <? require_once(APPLICATION_PATH.'/views/scripts/partial/horizontal_subnav2.phtml');?>
                <!-- dashboard nav end -->

                <div class="module-tools">
                    <div class="small-7 medium-7 large-7 columns">
                        <a class="addnew addnew-product"><i class="icon fi-plus"></i><span>Add a Product</span></a>
                    </div>
                    <div class="small-5 medium-5 large-5 columns">
                        <form action="" class="module-search glass-right" data-search>
                            <input type="text" class="search-input hidden">
                            <a href="javascript:;" class="search-submit"><i class="icon fi-magnifying-glass"></i></a>
                        </form>
                    </div>
                </div>
                <!-- sorting header end -->

                <div class="detail-wrap product-details products-reseller">
                    <header class="row detail-header">
                        <div class="large-12 columns">Details</div>
                    </header>
                    <div class="products-item-detail">
                        <?foreach($this->products as $product){?>
                        <form action="" data-abide="ajax" class="product-item">
                            <input type="hidden" name="id" class="product-id" value="<?=$product['id']?>">
                            <input type="hidden" name="resell" value="1">
                            <input type="hidden" name="quantity" value="1">
                            <div class="alert-field"></div>
                            <header class="row header">
                                <div class="small-6 medium-6 large-6 columns">
                                    <input type="submit" value="save" class="left module-button save-button">
                                </div>
                                <div class="small-6 medium-6 large-6 columns">
                                    <a href="javascript:;" class="right module-button delete-button">Delete</a>
                                </div>
                            </header>
                            <div class="item-row data-abide-input-container">
                                <div class="small-2 medium-2 large-2 columns">
                                    <label class="required">Source URL</label>
                                </div>
                                <div class="small-10 medium-10 large-10 columns">
                                    <input type="url" required value="<?=$product['purchase_url']?>" name="purchase_url">
                                    <small class="error">Source URL is required.</small>
                                </div>
                            </div>
                            <div class="item-row data-abide-input-container">
                                <div class="small-2 medium-2 large-2 columns">
                                    <label class="required">Images</label>
                                </div>
                                <div class="small-10 medium-10 large-10 columns">
                                    <input type="hidden" required pattern="^1$" value="<?=empty($product['pictures']) ? 0 :1?>" class="has_image">
                                    <ul class="images js-sortable">
                                        <?foreach($product['pictures'][45] as $i => $pic){ ?>
                                        <li class="image-item" picture-id="<?$i?>" product-id="<?=$product['id']?>">
                                            <img src="<?=$pic?>">
                                            <a href="javascript:;" class="delete-image">&times</a>
                                        </li>
                                        <?}?>
                                        <li class="add-image">
                                            <a href="javascript:;"><i class="icon fi-plus"></i></a>
                                        </li>
                                    </ul>
                                    <small class="error">Image is required</small>
                                </div>
                            </div>
                            <div class="item-row data-abide-input-container">
                                <div class="small-2 medium-2 large-2 columns">
                                    <label class="required">Name</label>
                                </div>
                                <div class="small-10 medium-10 large-10 columns">
                                    <input type="text" required value="<?=$product['name']?>" name="name">
                                    <small class="error">Name is required</small>
                                </div>
                            </div>
                            <div class="item-row">
                                <div class="small-2 medium-2 large-2 columns">Description</div>
                                <div class="small-10 medium-10 large-10 columns">
                                    <textarea name="description"><?=$product['description']?></textarea>
                                </div>
                            </div>
                            <div class="item-row data-abide-input-container">
                                <div class="small-2 medium-2 large-2 columns">
                                    <label class="required">Category</label>
                                </div>
                                <div class="small-10 medium-10 large-10 columns">
                                    <select name="global_category_id" required pattern="^[1-9][0-9]*">
                                        <option value="0"> ---- </option>
                                        <?foreach($this->global_categories as $cat){?>
                                        <option value="<?=$cat['id']?>" <?=$product['global_category_id'] == $cat['id'] ? 'seleced' : ''?>><?=$cat['path']?></option>
                                        <?}?>
                                    </select>
                                    <small class="error">Category is required</small>
                                </div>
                            </div>
                            <div class="item-row">
                                <div class="small-2 medium-2 large-2 columns">Tags</div>
                                <div class="small-10 medium-10 large-10 columns">
                                    <input type="text" name="categories" value="<?=$product['tags']?>">
                                </div>
                            </div>
                            <div class="item-row price-row data-abide-input-container">
                                <div class="small-2 medium-2 large-2 columns">
                                    <label class="required">Price</label>
                                </div>
                                <div class="small-10 medium-10 large-10 columns">
                                    <input type="text" placeholder="$" required name="price" value="<?=$product['price']?>">
                                    <small class="error">Price is required.</small>
                                </div>
                            </div>
                        </form>
                        <?}?>
                        <div class="text-center" style="height: 40px;">
                            <?php echo $this->pagination($this->total_rows, $this->rows_per_page, $this->page_num); ?>
                        </div>
                    </div>
                </div>
            </div>
            <!-- product detials end -->
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
