<link rel="stylesheet" href="/v2/css/pages/dashboard.css">
<div id="dashboard" class="row page-layout dashboard">

    <section class="small-12 medium-12 large-9 columns">
        <div class="row">
            <div class="small-3 medium-3 large-2 columns">
                <? require_once(APPLICATION_PATH . '/views/scripts/partial/left_sidebar.phtml'); ?>
            </div>
            <!-- side nav end -->

            <div id="sellingvenue-settings" class="small-9 medium-9 large-10 columns">
                <? require_once(APPLICATION_PATH . '/views/scripts/partial/horizontal_subnav.phtml'); ?>
                <!-- dashboard sub nav end -->

                <div class="row">
                    <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
                    <div class="small-8 medium-8 large-8 columns alert-field"></div>
                </div>

                <?if(!$this->is_subscriber && !$this->in_process) {?>
                <div class="large-12 columns">
                    <h3>Ready to launch? Awesome! - Here are our simple terms:</h3>
                    <ul style="font-weight:300;">
                        <li>30-Day Free Trial - Stop at anytime!</li>
                        <li>$4.99 USD per month after, no commitments</li>
                        <li>Sell up to 5,000 items in your store</li>
                        <li>Access to all our features & support</li>
                        <li>No PayPal fees for the first 90 days</li>
                        <li>3% fee paid to whoever helped you make a sale (you can add more!)</li>
                        <li>See the rest of our <a href="/terms">terms and conditions</a> here</li>
                    </ul>
                </div>
                <?if(APPLICATION_ENV === 'production') {?>
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" id="subscription-form" class="columns dashboard-form">
                    <div class="row field submit-field">
                        <div class="small-6 medium-6 large-6 columns">
                            <input type="hidden" name="cmd" value="_s-xclick">
                            <input type="hidden" name="hosted_button_id" value="2LEHDSTQF96SJ">
                            <input type="hidden" name="custom" value="<?=$this->store['id']?>" />
                            <input type="submit" name="submit" value="START FREE TRIAL" id="subscribe-button" class="submit-button">
                        </div>
                        <div class="small-6 medium-6 large-6 columns">
                            <a href="/dashboard" class="submit-button" style="padding: 0 10px">
                                Continue to Dashboard
                            </a>
                        </div>
                    </div>    
                </form>

                <?} else {?>
                <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top" id="subscription-form" class="columns dashboard-form">
                    <div class="row field submit-field">
                        <div class="small-6 medium-6 large-6 columns">
                            <input type="hidden" name="cmd" value="_s-xclick">
                            <input type="hidden" name="hosted_button_id" value="UNW2W5RYWWQPL">
                            <input type="hidden" name="custom" value="<?=$this->store['id']?>" />
                            <input type="submit" name="submit" value="START FREE TRIAL" id="subscribe-button" class="submit-button">
                        </div>
                        <div class="small-6 medium-6 large-6 columns">
                            <a href="/dashboard" class="submit-button" style="padding: 0 10px">
                                Continue to Dashboard
                            </a>
                        </div>
                    </div>
                </form>
                <?}?>
                <?} else if(!$this->is_subscriber && $this->in_process) {?>
                <p>We are processing your subscription request which normally takes no more than 3 minutes.</p>
                <div class="columns">
                    <div class="small-6 medium-6 large-6 columns">
                        <input type="submit" disabled name="submit" value="In Process" id="inprocess-button" class="submit-button">
                    </div>
                    <div class="small-6 medium-6 large-6 columns">
                        <a href="/dashboard" class="submit-button" style="padding: 0 10px">
                            Continue to Dashboard
                        </a>
                    </div>
                </div>
                <?} else if($this->is_subscriber) {?>
                <div class="columns">
                    <div class="small-6 medium-6 large-6 columns">
                        <?if(APPLICATION_ENV === 'production') {?>
                        <A HREF="https://www.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=HSJ8MFL6PKZA6" id="manage-button" class="submit-button" target="_blank" style="padding: 0 10px">
                            Manage Your Subscription
                        </A>
                        <?} else {?>
                        <A HREF="https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_subscr-find&alias=ELHK9S9QBTVBY"
                           id="manage-button" class="submit-button" target="_blank" style="padding: 0 10px">
                            Manage Your Subscription
                        </A>
                        <?}?>
                    </div>
                    <div class="small-6 medium-6 large-6 columns">
                        <a href="/dashboard" class="submit-button" style="padding: 0 10px">
                            Continue to Dashboard
                        </a>
                    </div>
                </div>
                <?}?>
            </div>
        </div>
    </section>

    <? require_once(APPLICATION_PATH . '/views/scripts/partial/right_sidebar.phtml'); ?>

</div>
