
<link rel="stylesheet" href="/v2/css/pages/dashboard.css">
<div id="dashboard" class="row page-layout dashboard">

    <section class="small-12 medium-12 large-9 columns">
        <div class="row">
            <div class="small-3 medium-3 large-2 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/left_sidebar.phtml');?>
            </div>
            <!-- side nav end -->

            <div id="sellingvenue-terms" class="small-9 medium-9 large-10 columns sellingvenue-terms">
                <div class="module-header">
                     <h2 class="title">Terms of Service</h2>
                 </div>
                 <p class="light">You must read, agree with and accept all of the terms and conditions contained in this User Agreement and the privacy policy before you may become a member of Shopintoit.</p>
                 <p class="light alert-field"></p>
                 <ol class="terms-list">
                    <li>We reserve the right to modify or terminate the Service for any reason, without notice at any time.</li>
                    <li>We reserve the right to refuse service to anyone for any reason at any time.</li>
                    <li>Your use of the Service is at your sole risk. The Service is provided on an ”as is“ and ”as available“ basis without any warranty or condition, express, implied or statutory.</li>
                    <li>Shopintoit does not warrant that the service will be uninterrupted, timely, secure, or error-free.</li>
                    <li>Shopintoit does not warrant that the results that may be obtained from the use of the service will be accurate or reliable.</li>
                    <li>You understand that your Content (not including credit card and other payment forms’ information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit Card information is always encrypted during transfer over networks.</li>
                 </ol>
                 <p class="text-center">
                     <a href="javascript:;" class="module-button agree-terms">Agree</a>
                 </p>
            </div>
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
