<link rel="stylesheet" href="/v2/css/pages/dashboard.css">
<div id="dashboard" class="row page-layout dashboard">

    <section class="small-12 medium-12 large-9 columns">
        <div class="row">
            <div class="small-3 medium-3 large-2 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/left_sidebar.phtml');?>
            </div>
            <!-- side nav end -->

            <div id="sellingvenue-accounts" class="small-9 medium-9 large-10 columns">
                <? require_once(APPLICATION_PATH.'/views/scripts/partial/horizontal_subnav.phtml');?>
                <!-- dashboard sub nav end -->

                <? require_once(APPLICATION_PATH.'/views/scripts/partial/horizontal_subnav2.phtml');?>
                <!-- dashboard nav end -->

                <p class="alert-field"></p>
                <form action="" data-abide="ajax" class="columns dashboard-form pinterest-info">
                    <div class="row field email-field data-abide-input-container">                        
                        <div class="small-4 medium-4 large-4 columns">
                            <label for="email" class="required">Pinterest Email Address</label>
                        </div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="email" name="email" required>
                            <small class="error">An email address is required.</small>                            
                        </div>
                    </div>
                    <div class="row field password-field data-abide-input-container">
                        <div class="small-4 medium-4 large-4 columns">
                            <label for="password" class="required">Pinterest Password</label>
                        </div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="password" name="password" required>
                            <small class="error">Password is required.</small>                             
                        </div>
                    </div>
                    <div class="row field submit-field">
                        <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="submit" value="Save" class="submit-button submit-pininfo">
                        </div>
                    </div>
                </form>

                <form action="" class="dashboard-form name-board" style="display:none;">
                    <div class="row field">
                        <div class="small-4 medium-4 large-4 columns">
                            <label for="boardname">Pinterest Board Name</label>
                        </div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input id="boardname" type="text" value="My Shopintoit Store">
                            <p class="tips">Would you like to pin to an existing board? <a href="javascript:;" class="show-selectboard">Click here »</a></p>
                        </div>
                    </div>
                    <div class="row field">
                        <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
                        <div class="small-8 medium-8 large-8 columns">
                            <input type="submit" value="Save" class="submit-button submit-nameboard">
                        </div>
                    </div>
                </form>

                <form action="" class="dashboard-form select-board" style="display:none;">
                    <div class="row field">
                         <div class="small-4 medium-4 large-4 columns">
                             <label for="selectboard">Select a Pinterest board</label>
                         </div>
                         <div class="small-8 medium-8 large-8 columns">
                            <select id="board_options"></select>
                            <p class="tips">Prefer to create a new board? <a href="javascript:;" class="show-nameboard">Click Here »</a></p>
                        </div>
                     </div>
                     <div class="row field">
                         <div class="small-4 medium-4 large-4 columns">&nbsp;</div>
                         <div class="small-8 medium-8 large-8 columns">
                            <input type="submit" value="Save" class="submit-button submit-selectboard">
                         </div>
                     </div>
                </form>

                <div class="pinning" style="display:none;">
                    <h5>We are pinning your products now.</h5>
                    <p>This process will take about 15 minutes so please check your Pinterest profile soon.</p>
                    <!-- <p><a class="module-button pin-more" href="javascript:;">Pin More</a></p>  -->
                </div>

            </div>
        </div>
    </section>

    <? require_once(APPLICATION_PATH.'/views/scripts/partial/right_sidebar.phtml');?>

</div>
