<?php

$page_acl = array(
    '/index/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    //'/login/index' => array('role' => array(ANONYMOUS), 'scheme' => HTTPS),
    '/join-now/index' => array('role' => array(ANONYMOUS), 'scheme' => HTTPS),
    '/logout/index' => array('role' => array(USER), 'scheme' => HTTP),
    '/orders/index' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/orders/item' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/payments/index' => array('role' => array(USER), 'scheme' => HTTPS),
    //'/store/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/info/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/store/info' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/store/products-item' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/cleancookie/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/terms/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/faqs/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/about/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/contact/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/merchant/seemore' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/merchant/coupon' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/merchant/shipping' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/account/verify' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/me/verify' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/ticket/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/feedback/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/errorlog/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/errorlog/print' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/error/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/pay/return' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/pay/cancel' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/pay/congrats' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/how/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/how/topics' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/index/test' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/search/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/pricing/index' => array('role' => array(ANONYMOUS), 'scheme' => HTTP),
    '/buyer-protection/index' => array('role' => array(ANONYMOUS), 'scheme' => HTTP),
    '/iframe/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/iframe/pinpicker' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/iframe/createproducts' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/iframe/createresellproducts' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/iframe/etsyimport' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/iframe/csvimport' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/referly/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/flashdeals/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/flashdealstest/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/merchant/customers' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/facebook/index' => array('role' => array(ANONYMOUS), 'scheme' => HTTP),
    '/facebook/test' => array('role' => array(ANONYMOUS), 'scheme' => HTTP),
    '/auction/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/auction/item' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/category/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),

    // api controllers
    '/api/getflashdealdetails' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/updateflashdealstatus' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/login' => array('role' => array(ANONYMOUS), 'scheme' => BOTH),
    '/api/setpayment' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/settransactionfee' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/importcontacts' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/addcustomer' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/deletecustomer' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/sendemail' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/send-email-to-us' => array('role' => array(ANONYMOUS, USER, MERCHANT), 'scheme' => BOTH),
    '/api/plogin' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/uploadpins' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/adminsavecategory' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/admindeletecategory' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/adminexchangecategoryrank' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/adminsavetag' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/admindeletetag' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/combo' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/test' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/deletecategory' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/updatepassword' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/storesearch' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/productsearch' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/savecategory' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/product-create' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/delete-product' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/updatepaymentitemstatus' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/updatepaymentstatus' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/createmasspay' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/downloadstoreinfo' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/downloaduserinfo' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/updateorder' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/checkout' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/resetpass' => array('role' => array(ANONYMOUS), 'scheme' => BOTH),
    '/api/get-abtests' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/add-abtest' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/delete-abtest' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/uploadstoreavater' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/updatefeaturedproduct' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/createproducts' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/importproductsfromcsv' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/updatepinterestusername' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/getboards' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/getpins' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/set-store-avatar' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/deleteproductcategory' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/deleteproductpicture' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/updateaccountstatus' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/categorizing' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/register' => array('role' => array(ANONYMOUS), 'scheme' => BOTH),
    '/api/excludeproduct' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/updateauctionstatus' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/bidauction' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/auctioncurrentbidprices' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/deletecoupon' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/admindeletecoupon' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/updatemerchantemail' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/add2cart' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/apply-coupon' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/clear-coupon' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/fulfill-order' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/cancel-order' => array('role' => array(MERCHANT, ADMIN), 'scheme' => BOTH),
    '/api/setordershipping' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/ncpaypalconfirm' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/ncpayment' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/nc-disburse' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/wallet-withdraw-request' => array('role' => array(USER), 'scheme' => BOTH),
    '/api/allowresell' => array('role' => array(ADMIN), 'scheme' => BOTH),
    '/api/resellproduct' => array('role' => array(MERCHANT), 'scheme' => BOTH),
    '/api/auth' => array('role' => array(ANONYMOUS), 'scheme' => BOTH),
    '/api/existeduser' => array('role' => array(ANONYMOUS), 'scheme' => BOTH),
    '/api/datatable' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/saveshippingopt' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/addshippingopt' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/deleteshippingopt' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/saveshippingdest' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/deleteshippingdest' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/saveproductshippingopt' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/deleteproductshippingopt' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/getdestination' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/savecustomfield' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/deletecustomfield' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/save-user-settings' => array('role' => array(USER), 'scheme' => HTTPS),
    '/api/save-selling-settings' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/register-merchant' => array('role' => array(USER), 'scheme' => HTTPS),
    '/api/save-credit-card' => array('role' => array(USER), 'scheme' => HTTPS),
    '/api/ticket' => array('role' => array(ANONYMOUS, USER), 'scheme' => BOTH),
    '/api/launch-store' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/ipn' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/api/inprocess' => array('role' => array(USER), 'scheme' => HTTPS),
    '/api/subscribed' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/api/close-store' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/api/is-login' => array('role' => array(USER), 'scheme' => HTTP),
    '/api/save-email-template' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/api/get-email-template' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/api/manage-store' => array('role' => array(ADMIN), 'scheme' => HTTPS),

    // admin controllers
    '/admin/index' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/stores' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/flashdeal' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/auction' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/listbids' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/payhistory' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/futurepay' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/featuredproduct' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/category' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/tags' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/email' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/email-templates' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/email-templates-edit' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/abtests' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/closeaccount' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/categorizing' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/coupon' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/nc-payment' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/payment-detail' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/users' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/store-detail' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/orders' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/annoucement' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/datatable' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/admin/amazon-products' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/dashboard/index' => array('role' => array(USER), 'scheme' => HTTPS),

    '/me/settings' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/orders-purchase' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/orders-purchase-detail' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/orders-resell' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/orders-resell-detail' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/wallet' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/wallet-detail' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/payment-accounts-paypal' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/payment-accounts-bank' => array('role' => array(USER), 'scheme' => HTTPS),
    '/me/payment-accounts-creditcard' => array('role' => array(USER), 'scheme' => HTTPS),

    '/selling/terms' => array('role' => array(USER), 'scheme' => HTTPS),
    '/selling/products' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/products-resell' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/products-shipping' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/orders' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/orders-detail' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/tools-analytics' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/tools-customers' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/tools-pinstore' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/tools-coupon' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/settings' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/preview' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/selling/subscription' => array('role' => array(ADMIN), 'scheme' => HTTPS),
    '/selling/close-store' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/solidus/index' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/solidus/publish' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/solidus/exchange' => array('role' => array(MERCHANT), 'scheme' => HTTPS),
    '/cart/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/checkout/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTPS),
    '/checkout/confirm' => array('role' => array(USER), 'scheme' => HTTPS),
    '/checkout/payment' => array('role' => array(USER), 'scheme' => HTTPS),
    '/checkout/paypalreturn' => array('role' => array(USER), 'scheme' => HTTPS),

    '/masonry/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),

    '/allstores/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/deals/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/shopbuilder/index' => array('role' => array(ANONYMOUS, USER), 'scheme' => HTTP),
    '/shutdown/index' => array('role' => array(ANONYMOUS, USER, ADMIN), 'scheme' => HTTP),
);
