    
    <div id="footer">
    <div id="footerSlogan"><span>“Get your Pinterest Store—easy and fast”</span></div>
    <div id="footerNav">
        <ul>
            <li><a href="#">LOGIN</a></li>
            <li><a href="#">ABOUT US</a></li>
            <li><a href="#">FAQS</a></li>
        </ul>
    </div>
    <div id="footerCopyright">&copy;2012 Pintics All rights reserved</div>
</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="http://platform.twitter.com/anywhere.js?id=tJxCAUaMG9IWY5xqYVrAQw&v=1" type="text/javascript"></script> 
<script src="/js/jquery.customforms.js"></script>
<script src="/js/jquery.orbit-1.4.0.js"></script>
<script src="/js/jquery.placeholder.min.js"></script>
<script src="/js/jquery.reveal.js"></script>
<script src="/js/jquery.tooltips.js"></script>
<script src="/js/modernizr.foundation.js"></script>
<script src="/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/js/app.js"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33040843-1']);
  _gaq.push(['_setDomainName', 'shopinterest.co']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>