

<link rel="stylesheet" type="text/css" href="/css/foundation.css">
<link rel="stylesheet" type="text/css" href="/css/page/affiliatestore_index.css">
<link href="http://fonts.googleapis.com/css?family=Josefin+Slab:700" rel="stylesheet" type="text/css">

<div id="feature">
        <div id="container" class="row">

            <div class="twelve columns ">
                <h1>
			<span id="span1">Special Shopinterest</span > selections for our friends from <span id="span2">refer.ly</span>
                </h1>
		
            </div>
        </div>

</div><!-- end container -->
<div class="page_body">
<div class="twelve columns contentbody" >
	    <!--first row start-->
               <div class="row fullwidth">
                    <div class="six columns right24" >
                        <div class="row">
                            <div class="five columns proInfo_left">
                                <div class="row ">
                                 
                                        <img class="prod_img"src="/img/product1.jpg"/>
                                    
                                </div>
                                <div class="row cat">
                                    <div class="three columns leftimg" >
                                        <img  src="/img/catseller.jpg"/>
                                    </div>
                                    <div class="nine columns rightdiv" >
                                        <p >Sold by</p>
            	                        <a href="#" alt="" >Store Name Here.</a>
                                    </div>
                               </div> <!-- 1st row 1st div left div ends-->
                       </div>
                       <div class="seven columns rightdescript">
                           <div class="prod_description" >
                                <div class="protitle">
                                    <h class="prod_title">Blue Silver Necklace</h>
                                    <p>Description copy here.Loren ipsum dolor adipiscing elit.Phasellus at auctor urna.</p>
                                </div>
                                <div class="only_price">
                                    <fieldset>
						<span id="fieldset1" >Only:</span>
						<span id="fieldset2" >$124.00</span>
						<br>
						<span id="fieldset3" >Commission </span>
						<span id="fieldset4" >15%</span>
				    </fieldset>
                                </div>
                                <div class="copy_address">
                                    <input class="eight columns" type="text"  value="http://www.refer.ly/phe">
							<button id="button1"class="button radius" >Copy URL</button>
                                </div>
                                <div class="ftpbuttons">
                                    <a href="#"><img src="/img/32x32-facebook.png"/></a>
                                    <a href="#"><img src="/img/32x32-twitter.png"/></a>
                                    <a href="#"><img src="/img/32x32-pinterest.png"/></a>
                                    <a href="#"><img src="/img/emailus.jpg"/></a>
                                </div>
                            </div>
                       </div>
		
                 </div>	
	   </div> 
                    <!-- first row first Div ends-->
           <div class="six columns right24" >
                        <div class="row">
                            <div class="five columns proInfo_left">
                                <div class="row">
                                    <div class="productimg" >
                                        <img class="prod_img"src="/img/product2.jpg"/>
                                    </div>
                                </div>
                                <div class="row cat">
                                    <div class="three columns leftimg" >
                                        <img  src="/img/catseller.jpg"/>
                                    </div>
                                    <div class="nine columns rightdiv" >
                                        <p >Sold by</p>
            	                        <a href="#" alt="" >Store Name Here.</a>
                                    </div>
                               </div> <!-- 1st row 1st div left div ends-->
                       </div>
                       <div class="seven columns rightdescript">
                           <div class="prod_description" >
                                <div class="protitle">
                                    <h class="prod_title">Blue Silver Necklace</h>
                                    <p>Description copy here.Loren ipsum dolor adipiscing elit.Phasellus at auctor urna.</p>
                                </div>
                                <div class="only_price">
                                    <fieldset>
						<span id="fieldset1" >Only:</span>
						<span id="fieldset2" >$124.00</span>
						<br>
						<span id="fieldset3" >Commission </span>
						<span id="fieldset4" >15%</span>
				    </fieldset>
                                </div>
                                <div class="copy_address">
                                    <input class="eight columns" type="text"  value="http://www.refer.ly/phe">
							<button id="button1"class="button radius" >Copy URL</button>
                                </div>
                                <div class="ftpbuttons">
                                    <a href="#"><img src="/img/32x32-facebook.png"/></a>
                                    <a href="#"><img src="/img/32x32-twitter.png"/></a>
                                    <a href="#"><img src="/img/32x32-pinterest.png"/></a>
                                    <a href="#"><img src="/img/emailus.jpg"/></a>
                                </div>
                            </div>
                       </div>
		
                 </div>	
	   </div> 
		 <!-- first row second Div ends-->
        </div>
         <!-- first row ends-->
        
        <div class="row fullwidth second" >
                    <div class="six columns right24" >
                        <div class="row">
                            <div class="five columns proInfo_left">
                                <div class="row">
                                    <div class="productimg" >
                                        <img class="prod_img"src="/img/product3.jpg"/>
                                    </div>
                                </div>
                                <div class="row cat">
                                    <div class="three columns leftimg" >
                                        <img  src="/img/catseller.jpg"/>
                                    </div>
                                    <div class="nine columns rightdiv" >
                                        <p >Sold by</p>
            	                        <a href="#" alt="" >Store Name Here.</a>
                                    </div>
                               </div> <!-- 2nd row 1st div left div ends-->
                       </div>
                       <div class="seven columns rightdescript">
                           <div class="prod_description" >
                                <div class="protitle">
                                    <h class="prod_title">Blue Silver Necklace</h>
                                    <p>Description copy here.Loren ipsum dolor adipiscing elit.Phasellus at auctor urna.</p>
                                </div>
                                <div class="only_price">
                                    <fieldset>
						<span id="fieldset1" >Only:</span>
						<span id="fieldset2" >$124.00</span>
						<br>
						<span id="fieldset3" >Commission </span>
						<span id="fieldset4" >15%</span>
				    </fieldset>
                                </div>
                                <div class="copy_address">
                                    <input class="eight columns" type="text"  value="http://www.refer.ly/phe">
							<button id="button1"class="button radius" >Copy URL</button>
                                </div>
                                <div class="ftpbuttons">
                                    <a href="#"><img src="/img/32x32-facebook.png"/></a>
                                    <a href="#"><img src="/img/32x32-twitter.png"/></a>
                                    <a href="#"><img src="/img/32x32-pinterest.png"/></a>
                                    <a href="#"><img src="/img/emailus.jpg"/></a>
                                </div>
                            </div>
                       </div>
		
                 </div>	
	   </div> 
                    <!-- second row first Div ends-->
           <div class="six columns right24" >
                        <div class="row ">
                            <div class="five columns proInfo_left">
                                <div class="row">
                                    <div class="productimg" >
                                        <img class="prod_img"src="/img/product4.jpg"/>
                                    </div>
                                </div>
                                <div class="row cat">
                                    <div class="three columns leftimg" >
                                        <img  src="/img/catseller.jpg"/>
                                    </div>
                                    <div class="nine columns rightdiv" >
                                        <p >Sold by</p>
            	                        <a href="#" alt="" >Store Name Here.</a>
                                    </div>
                               </div> <!-- 2nd row 1st div left div ends-->
                       </div>
                       <div class="seven columns rightdescript">
                           <div class="prod_description" >
                                <div class="protitle">
                                    <h class="prod_title">Blue Silver Necklace</h>
                                    <p>Description copy here.Loren ipsum dolor adipiscing elit.Phasellus at auctor urna.</p>
                                </div>
                                <div class="only_price">
                                    <fieldset>
						<span id="fieldset1" >Only:</span>
						<span id="fieldset2" >$124.00</span>
						<br>
						<span id="fieldset3" >Commission </span>
						<span id="fieldset4" >15%</span>
				    </fieldset>
                                </div>
                                <div class="copy_address">
                                    <input class="eight columns" type="text"  value="http://www.refer.ly/phe">
							<button id="button1"class="button radius" >Copy URL</button>
                                </div>
                                <div class="ftpbuttons">
                                    <a href="#"><img src="/img/32x32-facebook.png"/></a>
                                    <a href="#"><img src="/img/32x32-twitter.png"/></a>
                                    <a href="#"><img src="/img/32x32-pinterest.png"/></a>
                                    <a href="#"><img src="/img/emailus.jpg"/></a>
                                </div>
                            </div>
                       </div>
		
                 </div>	
	   </div> 
		 <!-- second row second Div ends-->
        </div>
           <!-- second row ends-->
        
        
       <div class="row fullwidth second" >
                    <div class="six columns right24" >
                        <div class="row">
                            <div class="five columns proInfo_left">
                                <div class="row">
                                    <div class="productimg" >
                                        <img class="prod_img"src="/img/product2.jpg"/>
                                    </div>
                                </div>
                                <div class="row cat">
                                    <div class="three columns leftimg" >
                                        <img  src="/img/catseller.jpg"/>
                                    </div>
                                    <div class="nine columns rightdiv" >
                                        <p >Sold by</p>
            	                        <a href="#" alt="" >Store Name Here.</a>
                                    </div>
                               </div> <!-- 3rd row 1st div left div ends-->
                       </div>
                       <div class="seven columns rightdescript">
                           <div class="prod_description" >
                                <div class="protitle">
                                    <h class="prod_title">Blue Silver Necklace</h>
                                    <p>Description copy here.Loren ipsum dolor adipiscing elit.Phasellus at auctor urna.</p>
                                </div>
                                <div class="only_price">
                                    <fieldset>
						<span id="fieldset1" >Only:</span>
						<span id="fieldset2" >$124.00</span>
						<br>
						<span id="fieldset3" >Commission </span>
						<span id="fieldset4" >15%</span>
				    </fieldset>
                                </div>
                                <div class="copy_address">
                                    <input class="eight columns" type="text"  value="http://www.refer.ly/phe">
							<button id="button1"class="button radius" >Copy URL</button>
                                </div>
                                <div class="ftpbuttons">
                                    <a href="#"><img src="/img/32x32-facebook.png"/></a>
                                    <a href="#"><img src="/img/32x32-twitter.png"/></a>
                                    <a href="#"><img src="/img/32x32-pinterest.png"/></a>
                                    <a href="#"><img src="/img/emailus.jpg"/></a>
                                </div>
                            </div>
                       </div>
		
                 </div>	
	   </div> 
                    <!-- third row first Div ends-->
           <div class="six columns right24" >
                        <div class="row">
                            <div class="five columns proInfo_left">
                                <div class="row">
                                    <div class="productimg" >
                                        <img class="prod_img"src="/img/product1.jpg"/>
                                    </div>
                                </div>
                                <div class="row cat">
                                    <div class="three columns leftimg" >
                                        <img  src="/img/catseller.jpg"/>
                                    </div>
                                    <div class="nine columns rightdiv" >
                                        <p >Sold by</p>
            	                        <a href="#" alt="" >Store Name Here.</a>
                                    </div>
                               </div> <!-- 3rd row 1st div left div ends-->
                       </div>
                       <div class="seven columns rightdescript">
                           <div class="prod_description" >
                                <div class="protitle">
                                    <h class="prod_title">Blue Silver Necklace</h>
                                    <p>Description copy here.Loren ipsum dolor adipiscing elit.Phasellus at auctor urna.</p>
                                </div>
                                <div class="only_price">
                                    <fieldset>
						<span id="fieldset1" >Only:</span>
						<span id="fieldset2" >$124.00</span>
                                                </br>
                                                <span id="fieldset3" >Commission </span>
						<span id="fieldset4" >15%</span>
				    </fieldset>
                                </div>
                                <div class="copy_address">
                                    <input id="input1" class="eight columns" type="text"  value="http://www.refer.ly/phe">
							<button id="button1"class="button radius" >Copy URL</button>
                                </div>
                                <div class="ftpbuttons">
                                    <a href="#"><img src="/img/32x32-facebook.png"/></a>
                                    <a href="#"><img src="/img/32x32-twitter.png"/></a>
                                    <a href="#"><img src="/img/32x32-pinterest.png"/></a>
                                    <a href="#"><img src="/img/emailus.jpg"/></a>
                                </div>
                            </div>
                       </div>
		
                 </div>	
	  
             </div> <!-- third row second Div ends-->
                      
        </div>  <!-- third row ends-->
</div>
        
</div>




