
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script type='text/javascript' src='http://code.jquery.com/jquery-2.0.3.min.js'></script>
        <script type='text/javascript' src='https://cdn.firebase.com/v0/firebase.js'></script>
        <script type='text/javascript' src='https://cdn.firebase.com/v0/firebase-simple-login.js'></script>
        <script type='text/javascript' src='/js/test.js'></script>
    </head>
    <body>
        <h3>Firebase Sign In</h3>
        <div class="container">
            <div>
                <a href="/test/firebase-clean-cookie">Clear Firebase Cookie</a>
            </div>
            <div>
                <a href="" class="login" action-type="facebook">Facebook SignIn</a>
            </div>
            <!--<div>
                <a href="" class="login" action-type="twitter">Twitter SignIn</a>
            </div>-->
            <div>
                <input type="text" id="email" placeholder="email"/>
                <input type="password" id="password" placeholder="password"/>
                <input type="submit" class="login" value="login" action-type="password">
                <input type="submit" class="signup" value="signup">
            </div>
        </div>
    </body>
</html>
