
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script type='text/javascript' src='http://code.jquery.com/jquery-2.0.3.min.js'></script>
        <script type='text/javascript' src='https://cdn.firebase.com/v0/firebase.js'></script>
        <script type='text/javascript' src='https://cdn.firebase.com/v0/firebase-simple-login.js'></script>
        <script type='text/javascript' src='/js/test.js'></script>
    </head>
    <body>
        <h3>Firebase Details</h3>
        <div>
            <a href="" class="logout">Logout</a>
        </div>
    </body>
</html>
