<link rel="stylesheet" type="text/css" href="/css/page/test_purchase.css">

<div id="container" class="row">
    <div class="twelve columns">


        <a name="head"> </a><h1>Your<span class="gentium"> Purchase </span> History</h1>
        <div class="row">
            <div class="panel tweleve columns centered">
                <div class="row">
                    <div class="twelve columns">  
                        <table id="purchasetable">
                            <thead>
                                <tr>
                                    <th class="orderno" >Order</th>
                                    <th class="productimage">Product Image</th>
                                    <th class="purchasedate" >Date</th>
                                    <th class="purchasestatus" >Status</th>
                                    <th class="amount" >Amount</th>
                                    <th class="purchasedetail">Details</th>
                                    <th class="domore" >I wanna...</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr text-align="center">
                                    <td class="ordernumber">No.51200</td>
                                    <td class=""><img src="http://placehold.it/100x100"></td>
                                    <td class="date">2013-05-09 05:25:27</td>
                                    <td class="fulfilment">Done</td>
                                    <td class="total">$988.57</td>
                                    <td class="total dropdowninput">Quantity: 1</br>Sold by:<a href="#">Chris' Store</a></td>
                                    <td class="domore"><div class="domorebuttons" >
                                            <img src="/img/32x32-facebook.png"  title="share on facebook" />
                                            <img src="/img/32x32-twitter.png" title="post on twitter" />
                                            <img src="/img/32x32-pinterest.png" title="pin on pinterest!"/></br>
                                            <a id="buyitbutton" href="#"  class="button radius">buy it again!</a></div>
                                    </td>
                                </tr>
                                <tr text-align="center">
                                    <td class="ordernumber">No.66300</td>
                                    <td class=""><img src="http://placehold.it/100x100"></td>
                                    <td class="date">2013-05-01 03:36:24</td>
                                    <td class="fulfilment">PENDING</td>
                                    <td class="total">$134.45</td>
                                    <td class="total dropdowninput">Quantity: 2</br>Sold by:<a href="#" style="text-decoration:underline;">Fancy Land</a></td>
                                    <td class="domore" ><div class="domorebuttons" >
                                            <img src="/img/32x32-facebook.png"  title="share on facebook" />
                                            <img src="/img/32x32-twitter.png" title="post on twitter" />
                                            <img src="/img/32x32-pinterest.png" title="pin on pinterest!" /></br>
                                            <a id="buyitbutton" href="#"  class="button radius">buy it again!</a></div>
                                    </td>

                                </tr>
                                <tr text-align="center">
                                    <td class="ordernumber">No.912408</td>
                                    <td class=""><img src="http://placehold.it/100x100"></td>
                                    <td class="date">2013-03-19 05:25:27</td>
                                    <td class="fulfilment">Done</td>
                                    <td class="total">$111.35</td>
                                    <td class="total dropdowninput">Quantity: 1</br>Sold by:<a href="#" style="text-decoration:underline;">Fashion world</a></td>
                                    <td class="domore" ><div class="domorebuttons" >
                                            <img src="/img/32x32-facebook.png"  title="share on facebook" />
                                            <img src="/img/32x32-twitter.png" title="post on twitter" />
                                            <img src="/img/32x32-pinterest.png" title="pin on pinterest!" /></br>
                                            <a href="#" id="buyitbutton" class="button radius">buy it again!</a></div>
                                    </td>

                               </tr>


                            </tbody>
                        </table>
                        <a href="#head"><span id="back2top">Back to top</span></a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

