<link rel="stylesheet" href="/v2/css/foundation.css"/>
<link rel="stylesheet" href="/v2/css/foundation-icons.css">
<link rel="stylesheet" href="/v2/css/common.css"/>
<link rel="stylesheet" href="/v2/css/modules.css"/>
<link rel="stylesheet" href="/css/simplePagination.css"/>
<script src="/v2/js/modernizr.js"></script>
<script src="/v2/js/jquery.js"></script>

<div>
    <a href="#" class="native_link" data-reveal>Click Me For A Modal</a>
</div>
<br><br>
<div>
    <a href="#" class="remote_link" data-reveal-ajax="true" data-reveal-id="myModal">
        Click Me For A AJAX Modal
    </a>
</div>

<div id="myModal" class="reveal-modal" data-reveal>
  <h2>Awesome. I have it.</h2>
  <p class="lead">Your couch.  It is mine.</p>
  <p>Im a cool paragraph that lives inside of an even cooler modal. Wins</p>
  <a class="close-reveal-modal">&#215;</a>
</div>


<form id="container">

<input type="submit" value="submit">




</form>

<script src="/js/jquery.simplePagination.js"></script>
<script src="/v2/js/foundation/foundation.js"></script>
<script src="/v2/js/foundation/foundation.abide.js"></script>
<script src="/v2/js/foundation/foundation.orbit.js"></script>
<script src="/v2/js/foundation/foundation.reveal.js"></script>
<script src="/v2/js/foundation/foundation.dropdown.js"></script>
<script src="/v2/js/foundation/foundation.topbar.js"></script>
<script src="/js/jquery.reveal.js"></script>
<script src="/js/jquery.placeholder.min.js"></script>
<script src="/js/jquery.cookie.js"></script>
<script src="/js/jquery.query.js"></script>
<script src="/js/mustache.js"></script>
<script src="/js/jquery.autocomplete.js"></script>
<script src="/js/imagesloaded.min.js"></script>
<script src="/js/libs/jquery-ui.js"></script>

<script>
    $('.native_link').click(function(e) {
        $('#myModal').foundation('reveal', 'open');
    });
    
    $('.remote_link').click(function(e) {
        $('#myModal').foundation('reveal', 'open', {
            url: 'http://www.staging.shopinterest.co:6083/test/echo',
            data: {param1: 'value1', param2: 'value2'}
        });
    });

    $('input[type="submit"]').click(function(e) {
        e.preventDefault();
        console.log("hello");
    });


</script>